#ifndef JAI_BOOT_SEED_H
#define JAI_BOOT_SEED_H

#include <stddef.h>

/* Prebuilt .jaic images for the modules the self-hosted front end needs before
 * it can compile anything -- including itself.
 *
 * The front end is written in Jaithon, so compiling it needs a Jaithon
 * compiler. During the `sLoadingFrontEnd` window,
 * `src/runtime/modules/module.c` loads the compiler's startup closure from this
 * seed. Once loaded, the compiler builds Jaithon source itself.
 *
 * Generated by `scripts/gen_seed.py`; regenerate with `make reseed`. */

typedef struct {
    /* Source path relative to the library root, e.g. "std/list.jai".
     *
     * Keyed on the path and not on the module name: the name an importer gives
     * a module is not always the dotted one. A relative import
     * (`from .chunk import ...`) names it `chunk`, so a name-keyed seed is
     * unreachable for every module reached that way -- which was most of the
     * compiler, and is why the seed never served the bootstrap window. */
    const char          *module;
    const unsigned char *image;    /* serialised .jaic */
    size_t               length;
} JaiSeedEntry;

/* The seeded image for `module`, or NULL when the seed does not carry it.
 * A miss is not an error: outside the bootstrap window modules are compiled
 * from source as usual. */
const JaiSeedEntry *jaiSeedFind(const char *sourcePath);

/* How many modules the seed carries. Zero in a build with no seed, which is a
 * build that still needs a working front end on disk to start. */
size_t jaiSeedCount(void);

#endif /* JAI_BOOT_SEED_H */
