#ifndef JAI_BOOT_SEED_H
#define JAI_BOOT_SEED_H

#include <stddef.h>

/* Prebuilt .jaic images for the modules the self-hosted front end needs before
 * it can compile anything -- including itself.
 *
 * The front end is written in Jaithon, so compiling it needs a Jaithon
 * compiler. `src/runtime/module.c` breaks that circle with the
 * `sLoadingFrontEnd` window, inside which the C front end compiles the
 * compiler's own closure. The seed lets that window be served from the binary
 * instead, which is what makes deleting the C front end possible: everything
 * outside the window is already self-hosted.
 *
 * Generated by `scripts/gen_seed.py`; regenerate with `make reseed`. */

typedef struct {
    const char          *module;   /* dotted name, e.g. "std.list" */
    const unsigned char *image;    /* serialised .jaic */
    size_t               length;
} JaiSeedEntry;

/* The seeded image for `module`, or NULL when the seed does not carry it.
 * A miss is not an error: outside the bootstrap window modules are compiled
 * from source as usual. */
const JaiSeedEntry *jaiSeedFind(const char *module);

/* How many modules the seed carries. Zero in a build with no seed, which is a
 * build that still needs a working front end on disk to start. */
size_t jaiSeedCount(void);

#endif /* JAI_BOOT_SEED_H */
