/* Generated by scripts/gen_seed.py. Do not edit.
 *
 * The index over boot/seed.bin, which holds the .jaic images the
 * self-hosted front end needs before it can compile anything --
 * including itself. The images are deflated one per module and
 * inflated on first use, so a program pays for what it imports.
 *
 * 42 modules, 1585712 bytes of images, 708972 bytes packed.
 * Regenerate with `make reseed`.
 */

#include "boot/seed.h"

#include <stdlib.h>
#include <string.h>
#include <zlib.h>

/* Defined by boot/seed_blob.S. */
extern const unsigned char jaiSeedBlob[];

typedef struct {
    const char *module;
    size_t      offset;   /* into jaiSeedBlob */
    size_t      packed;   /* deflated size */
    size_t      raw;      /* size once inflated */
} SeedSource;

static const SeedSource kSources[] = {
    {"jaithon/ast.jai", 0, 32598, 76254},
    {"jaithon/ast_encode.jai", 32598, 25029, 55567},
    {"jaithon/ast_unparse.jai", 57627, 29572, 66272},
    {"jaithon/compile/check/assign.jai", 87199, 4883, 11216},
    {"jaithon/compile/check/checker.jai", 92082, 20848, 45006},
    {"jaithon/compile/check/ctx.jai", 112930, 22587, 52958},
    {"jaithon/compile/check/decl.jai", 135517, 32995, 72826},
    {"jaithon/compile/check/expr.jai", 168512, 42192, 90829},
    {"jaithon/compile/check/fold.jai", 210704, 16346, 37937},
    {"jaithon/compile/check/kinds.jai", 227050, 1534, 3181},
    {"jaithon/compile/check/modsig.jai", 228584, 10332, 22828},
    {"jaithon/compile/check/nominal.jai", 238916, 3771, 9168},
    {"jaithon/compile/check/operator.jai", 242687, 5974, 13716},
    {"jaithon/compile/check/predicate.jai", 248661, 2690, 6298},
    {"jaithon/compile/check/relate.jai", 251351, 2026, 4199},
    {"jaithon/compile/check/render.jai", 253377, 3501, 7469},
    {"jaithon/compile/check/stmt.jai", 256878, 37875, 82965},
    {"jaithon/compile/check/substitute.jai", 294753, 2619, 5587},
    {"jaithon/compile/check/suggest.jai", 297372, 2548, 5327},
    {"jaithon/compile/check/ty.jai", 299920, 2698, 6251},
    {"jaithon/compile/check/union.jai", 302618, 2434, 5051},
    {"jaithon/compile/check/universe.jai", 305052, 3386, 7488},
    {"jaithon/compile/diag.jai", 308438, 3396, 7723},
    {"jaithon/compile/emit.jai", 311834, 76810, 172575},
    {"jaithon/compile/jaic.jai", 388644, 28228, 60619},
    {"jaithon/compile/lexer.jai", 416872, 32292, 72600},
    {"jaithon/compile/mod.jai", 449164, 8652, 18551},
    {"jaithon/compile/opt/chunk.jai", 457816, 18146, 40631},
    {"jaithon/compile/opt/coalesce.jai", 475962, 5023, 10700},
    {"jaithon/compile/opt/dead.jai", 480985, 495, 909},
    {"jaithon/compile/opt/fuse.jai", 481480, 10372, 23080},
    {"jaithon/compile/opt/hoist.jai", 491852, 7301, 15176},
    {"jaithon/compile/opt/mod.jai", 499153, 1960, 4052},
    {"jaithon/compile/opt/peephole.jai", 501113, 8484, 18365},
    {"jaithon/compile/parser.jai", 509597, 78511, 182242},
    {"jaithon/compile/repl.jai", 588108, 6036, 13073},
    {"jaithon/compile/resolve.jai", 594144, 35978, 80155},
    {"jaithon/compile/symbol.jai", 630122, 4883, 10967},
    {"jaithon/compile/token.jai", 635005, 11215, 26385},
    {"std/json.jai", 646220, 23774, 52137},
    {"std/math.jai", 669994, 16605, 38785},
    {"std/str.jai", 686599, 22373, 48594},
};

#define JAI_SEED_N (sizeof kSources / sizeof kSources[0])

/* Inflated on demand and kept. Never freed: the images outlive
 * every caller and the process is the only thing that ends. */
static JaiSeedEntry kEntries[JAI_SEED_N];

static const JaiSeedEntry *unpack(size_t i) {
    if (kEntries[i].image != NULL) return &kEntries[i];
    size_t raw = kSources[i].raw;
    unsigned char *out = malloc(raw ? raw : 1);
    if (out == NULL) return NULL;
    uLongf got = (uLongf)raw;
    if (uncompress(out, &got, jaiSeedBlob + kSources[i].offset,
                   (uLong)kSources[i].packed) != Z_OK ||
        got != raw) {
        /* A corrupt seed must fail to load rather than load
         * something nearly right; the caller answers a NULL by
         * compiling from source. */
        free(out);
        return NULL;
    }
    kEntries[i].module = kSources[i].module;
    kEntries[i].image  = out;
    kEntries[i].length = raw;
    return &kEntries[i];
}

/* The caller has an absolute path and the table holds paths
 * relative to the library root, so a key matches when it is a
 * trailing path component run of the argument. Anchoring on the
 * separator is what stops `list.jai` from matching
 * `mylist.jai`. */
const JaiSeedEntry *jaiSeedFind(const char *sourcePath) {
    if (sourcePath == NULL) return NULL;
    size_t pathLen = strlen(sourcePath);
    for (size_t i = 0; i < JAI_SEED_N; i++) {
        size_t keyLen = strlen(kSources[i].module);
        if (keyLen > pathLen) continue;
        const char *tail = sourcePath + (pathLen - keyLen);
        if (strcmp(tail, kSources[i].module) != 0) continue;
        if (tail != sourcePath && tail[-1] != '/') continue;
        return unpack(i);
    }
    return NULL;
}

size_t jaiSeedCount(void) { return JAI_SEED_N; }
