/* Generated by scripts/gen_seed.py. Do not edit.
 *
 * The index over boot/seed.bin, which holds the .jaic images the
 * self-hosted front end needs before it can compile anything --
 * including itself. The images are deflated one per module and
 * inflated on first use, so a program pays for what it imports.
 *
 * 42 modules, 1588999 bytes of images, 710477 bytes packed.
 * Regenerate with `make reseed`.
 */

#include "boot/seed.h"

#include <stdlib.h>
#include <string.h>
#include <zlib.h>

/* Defined by boot/seed_blob.S. */
extern const unsigned char jaiSeedBlob[];

typedef struct {
    const char *module;
    size_t      offset;   /* into jaiSeedBlob */
    size_t      packed;   /* deflated size */
    size_t      raw;      /* size once inflated */
} SeedSource;

static const SeedSource kSources[] = {
    {"jaithon/ast.jai", 0, 32599, 76254},
    {"jaithon/ast_encode.jai", 32599, 25028, 55567},
    {"jaithon/ast_unparse.jai", 57627, 29572, 66272},
    {"jaithon/compile/check/assign.jai", 87199, 4883, 11216},
    {"jaithon/compile/check/checker.jai", 92082, 20869, 45006},
    {"jaithon/compile/check/ctx.jai", 112951, 22588, 52958},
    {"jaithon/compile/check/decl.jai", 135539, 32994, 72826},
    {"jaithon/compile/check/expr.jai", 168533, 42191, 90829},
    {"jaithon/compile/check/fold.jai", 210724, 16348, 37937},
    {"jaithon/compile/check/kinds.jai", 227072, 1529, 3181},
    {"jaithon/compile/check/modsig.jai", 228601, 11015, 24340},
    {"jaithon/compile/check/nominal.jai", 239616, 3770, 9168},
    {"jaithon/compile/check/operator.jai", 243386, 5975, 13716},
    {"jaithon/compile/check/predicate.jai", 249361, 2689, 6298},
    {"jaithon/compile/check/relate.jai", 252050, 2026, 4199},
    {"jaithon/compile/check/render.jai", 254076, 3501, 7469},
    {"jaithon/compile/check/stmt.jai", 257577, 37875, 82965},
    {"jaithon/compile/check/substitute.jai", 295452, 2618, 5587},
    {"jaithon/compile/check/suggest.jai", 298070, 2549, 5327},
    {"jaithon/compile/check/ty.jai", 300619, 2698, 6251},
    {"jaithon/compile/check/union.jai", 303317, 2434, 5051},
    {"jaithon/compile/check/universe.jai", 305751, 3385, 7488},
    {"jaithon/compile/diag.jai", 309136, 3397, 7723},
    {"jaithon/compile/emit.jai", 312533, 77626, 174350},
    {"jaithon/compile/jaic.jai", 390159, 28237, 60619},
    {"jaithon/compile/lexer.jai", 418396, 32291, 72600},
    {"jaithon/compile/mod.jai", 450687, 8644, 18551},
    {"jaithon/compile/opt/chunk.jai", 459331, 18132, 40631},
    {"jaithon/compile/opt/coalesce.jai", 477463, 5022, 10700},
    {"jaithon/compile/opt/dead.jai", 482485, 495, 909},
    {"jaithon/compile/opt/fuse.jai", 482980, 10374, 23080},
    {"jaithon/compile/opt/hoist.jai", 493354, 7301, 15176},
    {"jaithon/compile/opt/mod.jai", 500655, 1958, 4052},
    {"jaithon/compile/opt/peephole.jai", 502613, 8485, 18365},
    {"jaithon/compile/parser.jai", 511098, 78509, 182242},
    {"jaithon/compile/repl.jai", 589607, 6041, 13073},
    {"jaithon/compile/resolve.jai", 595648, 35980, 80155},
    {"jaithon/compile/symbol.jai", 631628, 4885, 10967},
    {"jaithon/compile/token.jai", 636513, 11216, 26385},
    {"std/json.jai", 647729, 23774, 52137},
    {"std/math.jai", 671503, 16604, 38785},
    {"std/str.jai", 688107, 22370, 48594},
};

#define JAI_SEED_N (sizeof kSources / sizeof kSources[0])

/* Inflated on demand and kept. Never freed: the images outlive
 * every caller and the process is the only thing that ends. */
static JaiSeedEntry kEntries[JAI_SEED_N];

static const JaiSeedEntry *unpack(size_t i) {
    if (kEntries[i].image != NULL) return &kEntries[i];
    size_t raw = kSources[i].raw;
    unsigned char *out = malloc(raw ? raw : 1);
    if (out == NULL) return NULL;
    uLongf got = (uLongf)raw;
    if (uncompress(out, &got, jaiSeedBlob + kSources[i].offset,
                   (uLong)kSources[i].packed) != Z_OK ||
        got != raw) {
        /* A corrupt seed must fail to load rather than load
         * something nearly right; the caller answers a NULL by
         * compiling from source. */
        free(out);
        return NULL;
    }
    kEntries[i].module = kSources[i].module;
    kEntries[i].image  = out;
    kEntries[i].length = raw;
    return &kEntries[i];
}

/* The caller has an absolute path and the table holds paths
 * relative to the library root, so a key matches when it is a
 * trailing path component run of the argument. Anchoring on the
 * separator is what stops `list.jai` from matching
 * `mylist.jai`. */
const JaiSeedEntry *jaiSeedFind(const char *sourcePath) {
    if (sourcePath == NULL) return NULL;
    size_t pathLen = strlen(sourcePath);
    for (size_t i = 0; i < JAI_SEED_N; i++) {
        size_t keyLen = strlen(kSources[i].module);
        if (keyLen > pathLen) continue;
        const char *tail = sourcePath + (pathLen - keyLen);
        if (strcmp(tail, kSources[i].module) != 0) continue;
        if (tail != sourcePath && tail[-1] != '/') continue;
        return unpack(i);
    }
    return NULL;
}

size_t jaiSeedCount(void) { return JAI_SEED_N; }
