/* Generated by scripts/dev/gen_seed.py. Do not edit.
 *
 * The index over boot/seed.bin, which holds the .jaic images the
 * self-hosted front end needs before it can compile anything --
 * including itself. The images are stored raw, each on a 16-byte
 * boundary, and served in place from the binary's read-only data:
 * nothing is copied or inflated at run time.
 *
 * 99 modules, 877292 bytes of images, 878048 bytes with padding.
 * Regenerate with `make reseed`.
 */

#include "boot/seed.h"

#include <string.h>

/* Defined by boot/seed_blob.S. */
extern const unsigned char jaiSeedBlob[];

typedef struct {
    const char *module;
    size_t      keyLen;   /* strlen(module) */
    size_t      offset;   /* into jaiSeedBlob */
    size_t      length;   /* the image's size */
} SeedSource;

static const SeedSource kSources[] = {
    {"jaithon/ast.jai", 15, 0, 1735},
    {"jaithon/ast/kinds.jai", 21, 1744, 5958},
    {"jaithon/ast/node.jai", 20, 7712, 11948},
    {"jaithon/ast/operators.jai", 25, 19664, 3346},
    {"jaithon/ast/schema.jai", 22, 23024, 11306},
    {"jaithon/ast/span.jai", 20, 34336, 2774},
    {"jaithon/ast/tree.jai", 20, 37120, 5127},
    {"jaithon/ast/types.jai", 21, 42256, 3346},
    {"jaithon/ast_encode.jai", 22, 45616, 27186},
    {"jaithon/ast_unparse.jai", 23, 72816, 32408},
    {"jaithon/compile/check/assign.jai", 32, 105232, 5992},
    {"jaithon/compile/check/checker.jai", 33, 111232, 23444},
    {"jaithon/compile/check/ctx.jai", 29, 134688, 26373},
    {"jaithon/compile/check/decl.jai", 30, 161072, 33734},
    {"jaithon/compile/check/expr.jai", 30, 194816, 43492},
    {"jaithon/compile/check/fold.jai", 30, 238320, 17850},
    {"jaithon/compile/check/kinds.jai", 31, 256176, 1795},
    {"jaithon/compile/check/modsig.jai", 32, 257984, 25286},
    {"jaithon/compile/check/nominal.jai", 33, 283280, 4353},
    {"jaithon/compile/check/operator.jai", 34, 287648, 6286},
    {"jaithon/compile/check/predicate.jai", 35, 293936, 3120},
    {"jaithon/compile/check/relate.jai", 32, 297056, 2177},
    {"jaithon/compile/check/render.jai", 32, 299248, 3812},
    {"jaithon/compile/check/stmt.jai", 30, 303072, 1568},
    {"jaithon/compile/check/substitute.jai", 36, 304640, 2740},
    {"jaithon/compile/check/suggest.jai", 33, 307392, 2527},
    {"jaithon/compile/check/ty.jai", 28, 309920, 3375},
    {"jaithon/compile/check/union.jai", 31, 313296, 2529},
    {"jaithon/compile/check/universe.jai", 34, 315840, 4007},
    {"jaithon/compile/diag.jai", 24, 319856, 4413},
    {"jaithon/compile/emit.jai", 24, 324272, 1568},
    {"jaithon/compile/emit/chunk.jai", 30, 325840, 5177},
    {"jaithon/compile/emit/emitter.jai", 32, 331024, 274},
    {"jaithon/compile/emit/opcode.jai", 31, 331312, 13787},
    {"jaithon/compile/emit/spec.jai", 29, 345104, 2496},
    {"jaithon/compile/jaic.jai", 24, 347600, 1585},
    {"jaithon/compile/lexer.jai", 25, 349200, 39635},
    {"jaithon/compile/mod.jai", 23, 388848, 10880},
    {"jaithon/compile/opt/chunk.jai", 29, 399728, 20876},
    {"jaithon/compile/opt/coalesce.jai", 32, 420608, 5119},
    {"jaithon/compile/opt/dead.jai", 28, 425728, 508},
    {"jaithon/compile/opt/fuse.jai", 28, 426240, 11927},
    {"jaithon/compile/opt/hoist.jai", 29, 438176, 7524},
    {"jaithon/compile/opt/mod.jai", 27, 445712, 2105},
    {"jaithon/compile/opt/peephole.jai", 32, 447824, 10228},
    {"jaithon/compile/parse/decl.jai", 30, 458064, 21026},
    {"jaithon/compile/parse/expr.jai", 30, 479104, 12511},
    {"jaithon/compile/parse/node_build.jai", 36, 491616, 4943},
    {"jaithon/compile/parse/pattern.jai", 33, 496560, 7192},
    {"jaithon/compile/parse/predicate.jai", 35, 503760, 4186},
    {"jaithon/compile/parse/primary.jai", 33, 507952, 14703},
    {"jaithon/compile/parse/state.jai", 31, 522656, 16125},
    {"jaithon/compile/parse/stmt.jai", 30, 538784, 14640},
    {"jaithon/compile/parse/token_class.jai", 37, 553424, 3067},
    {"jaithon/compile/parse/type_expr.jai", 35, 556496, 5202},
    {"jaithon/compile/parse/wire.jai", 30, 561712, 1712},
    {"jaithon/compile/parser.jai", 26, 563424, 343},
    {"jaithon/compile/repl.jai", 24, 563776, 5950},
    {"jaithon/compile/resolve.jai", 27, 569728, 348},
    {"jaithon/compile/symbol.jai", 26, 570080, 6448},
    {"jaithon/compile/token.jai", 25, 576528, 15268},
    {"std/json.jai", 12, 591808, 26098},
    {"std/math.jai", 12, 617920, 20028},
    {"std/str.jai", 11, 637952, 23249},
    {"jaithon/compile/jaic/bits.jai", 29, 661216, 3054},
    {"jaithon/compile/jaic/code.jai", 29, 664272, 1977},
    {"jaithon/compile/jaic/disassemble.jai", 36, 666256, 5751},
    {"jaithon/compile/jaic/format.jai", 31, 672016, 1162},
    {"jaithon/compile/jaic/linetable.jai", 34, 673184, 1843},
    {"jaithon/compile/jaic/model.jai", 30, 675040, 1745},
    {"jaithon/compile/jaic/read.jai", 29, 676800, 10190},
    {"jaithon/compile/jaic/stream.jai", 31, 686992, 3886},
    {"jaithon/compile/jaic/write.jai", 30, 690880, 7836},
    {"jaithon/compile/check/stmt/codes.jai", 36, 698720, 966},
    {"jaithon/compile/check/stmt/fields.jai", 37, 699696, 915},
    {"jaithon/compile/check/stmt/flow.jai", 35, 700624, 7536},
    {"jaithon/compile/check/stmt/function.jai", 39, 708160, 7093},
    {"jaithon/compile/check/stmt/matching.jai", 39, 715264, 8219},
    {"jaithon/compile/check/stmt/pattern.jai", 38, 723488, 9601},
    {"jaithon/compile/check/stmt/store.jai", 36, 733104, 10519},
    {"jaithon/compile/resolve/decl.jai", 32, 743632, 13555},
    {"jaithon/compile/resolve/predicate.jai", 37, 757200, 1630},
    {"jaithon/compile/resolve/resolver.jai", 36, 758832, 14898},
    {"jaithon/compile/resolve/scope.jai", 33, 773744, 1282},
    {"jaithon/compile/resolve/walk.jai", 32, 775040, 12603},
    {"jaithon/compile/resolve/wire.jai", 32, 787648, 783},
    {"jaithon/compile/emit/assert_text.jai", 36, 788432, 1317},
    {"jaithon/compile/emit/decl.jai", 29, 789760, 6770},
    {"jaithon/compile/emit/exception.jai", 34, 796544, 5628},
    {"jaithon/compile/emit/expr.jai", 29, 802176, 18495},
    {"jaithon/compile/emit/field_kind.jai", 35, 820672, 1633},
    {"jaithon/compile/emit/function.jai", 33, 822320, 4659},
    {"jaithon/compile/emit/iteration.jai", 34, 826992, 4531},
    {"jaithon/compile/emit/operator.jai", 33, 831536, 2129},
    {"jaithon/compile/emit/pattern.jai", 32, 833680, 14143},
    {"jaithon/compile/emit/shape.jai", 30, 847824, 2191},
    {"jaithon/compile/emit/state.jai", 30, 850016, 17562},
    {"jaithon/compile/emit/stmt.jai", 29, 867584, 9357},
    {"jaithon/compile/emit/wire.jai", 29, 876944, 1098},
};

#define JAI_SEED_N (sizeof kSources / sizeof kSources[0])

static JaiSeedEntry kEntries[JAI_SEED_N];

static const JaiSeedEntry *unpack(size_t i) {
    if (kEntries[i].image == NULL) {
        kEntries[i].module = kSources[i].module;
        kEntries[i].image  = jaiSeedBlob + kSources[i].offset;
        kEntries[i].length = kSources[i].length;
    }
    return &kEntries[i];
}

/* The caller has an absolute path and the table holds paths
 * relative to the library root, so a key matches when it is a
 * trailing path component run of the argument. Anchoring on the
 * separator is what stops `list.jai` from matching
 * `mylist.jai`. */
const JaiSeedEntry *jaiSeedFind(const char *sourcePath) {
    if (sourcePath == NULL) return NULL;
    size_t pathLen = strlen(sourcePath);
    for (size_t i = 0; i < JAI_SEED_N; i++) {
        size_t keyLen = kSources[i].keyLen;
        if (keyLen > pathLen) continue;
        const char *tail = sourcePath + (pathLen - keyLen);
        if (memcmp(tail, kSources[i].module, keyLen) != 0) continue;
        if (tail != sourcePath && tail[-1] != '/') continue;
        return unpack(i);
    }
    return NULL;
}

size_t jaiSeedCount(void) { return JAI_SEED_N; }

const char *jaiSeedModuleAt(size_t i) {
    return i < JAI_SEED_N ? kSources[i].module : NULL;
}

size_t jaiSeedPeekAt(size_t i, unsigned char *out, size_t n) {
    if (i >= JAI_SEED_N || out == NULL || n == 0) return 0;
    if (n > kSources[i].length) n = kSources[i].length;
    memcpy(out, jaiSeedBlob + kSources[i].offset, n);
    return n;
}
