#!/usr/bin/env python3
"""Differential fuzzer for the control flow the other two fuzzers never emit.

kind_mutation.py and iter_mutation.py hold the SHAPE fixed and vary a kind.
This one varies the shape -- try/catch (caught and propagating), defer
(including on an early return and while an exception unwinds), labelled break
and continue, match, returns from deep inside nested loops, closures called
after the local they captured moved on, and bounded recursion -- while keeping
the tag-lie bias that found the last three bugs: a `mode` parameter decides
which branch a slot is written on, and main warms ONE mode before calling the
rest, so every compiled specialisation is built from mode 0 and then violated.

    python3 tests/fuzz/control_flow.py                 # 200 programs
    python3 tests/fuzz/control_flow.py --count 500
    python3 tests/fuzz/control_flow.py --seed 1234 --keep
    python3 tests/fuzz/control_flow.py --compile-rate 100

Exit status is non-zero if any program disagrees with the interpreter.
"""

import argparse
import os
import random
import shutil
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
JAITHON = os.path.join(ROOT, "jaithon")

PROBE = "cfprobe"
WARM = 300

# Mode 0 is what main warms with, so every compiled body is specialised to the
# int arm; modes 1..5 are the kinds that arrive afterwards.
SLOT_ARMS = ['"s{k}"', "null", "Node({i})", "[{k}, {j}]", "{k}.5", "true"]
NMODES = len(SLOT_ARMS) + 1

ERRORS = ("ValueError", "TypeError", "IndexError", "KeyError", "RuntimeError")

# Chosen per program, not per statement. A closure call refuses the function
# tier outright (OP_CALL) and `match` stops the walk dead, so sprinkling them
# everywhere would leave every program half interpreted and the oracle
# comparing the interpreter with itself.
FEATURES = ("closure", "recurse", "unwind", "match", "defer", "late",
            "nullable", "retkind")

HELPERS = {
    "rsum": """
fn rsum(n: int) -> int {
    if n <= 0 { return 0 }
    return n + rsum(n - 1)
}
""",
    "rping": """
fn rping(n: int) -> int {
    if n <= 0 { return 1 }
    return rpong(n - 1)
}

fn rpong(n: int) -> int {
    if n <= 0 { return 0 }
    return rping(n - 1) + 1
}
""",
    # A raise that unwinds through N compiled frames, each with a defer to run.
    # The catch lives in its own function: a call that can raise inside a try
    # refuses the enclosing body outright, and cfprobe must keep compiling.
    "unwind": """
fn rthrow(n: int, out: list) -> int {
    defer { out.push(9) }
    if n <= 0 { throw ValueError("deep") }
    return rthrow(n - 1, out) + 1
}

fn unwind(n: int, out: list) -> int {
    try {
        return rthrow(n, out)
    } catch _e: ValueError {
        return n * 2
    }
}
""",
    # `for h in fs` refuses a body outright ("iterating a list with nothing to
    # look at"), so the closures a loop collected are called from here instead.
    "drain": """
fn drain(fs: list) -> int {
    var t = 0
    for h in fs { t = t + h() }
    return t
}
""",
    # A callee whose RETURN kind is decided by a branch, not by an argument.
    # The unreachable first `return` is load-bearing: a one-expression body is
    # inlined outright, and then there is no call left to predict a kind for.
    "branchy": """
fn branchy(n: int, mode: int) -> any {
    if n > 1000000000 { return "never" }
    if mode >= 3 { return "s" }
    return n
}
""",
    "make_adder": """
fn make_adder(k: int) -> fn(int) -> int {
    return |x| x + k
}
""",
}

PRELUDE = """#: Generated by tests/fuzz/control_flow.py --seed {seed}. Do not edit.
class Node {{
    pub var n: int
    fn init(self, n: int) {{ self.n = n }}
    pub fn __str__(self) -> str {{ return f"N{{self.n}}" }}
}}
"""

ATTEMPT = """
fn attempt(mode: int, out: list) -> str {{
    try {{
        return {probe}(mode, out)
    }} catch _e: TypeError {{
        return "TypeError"
    }} catch _e: ValueError {{
        return "ValueError"
    }} catch _e: IndexError {{
        return "IndexError"
    }} catch _e: KeyError {{
        return "KeyError"
    }} catch _e: DivisionByZeroError {{
        return "DivisionByZeroError"
    }} catch _e: RuntimeError {{
        return "RuntimeError"
    }} catch _e: Error {{
        return "Error"
    }}
}}

fn main() -> int {{
    var sink: list = []
    var w = ""
    for _r in 0..{warm} {{ w = attempt(0, sink) }}
    print(w)
    for m in 0..{modes} {{
        var out: list = []
        print(attempt(m, out))
        print(out)
    }}
    for _r in 0..{warm} {{ w = attempt(0, sink) }}
    print(w)
    for m in 0..{modes} {{
        var out: list = []
        print(attempt(m, out))
        print(out)
    }}
    return 0
}}
"""


class Gen:
    """One program. Every loop bound is a literal, so every program halts."""

    def __init__(self, seed):
        self.rng = random.Random(seed)
        self.seed = seed
        self.helpers = set()
        self.features = {f for f in FEATURES if self.rng.random() < 0.4}
        self.in_try = 0
        self.pre = []
        self.post = []
        self.uid = 0

    def n(self):
        self.uid += 1
        return self.uid

    # -- expressions ------------------------------------------------------
    def ivar(self, loopvars):
        return self.rng.choice(loopvars + ["mode", "cap"])

    def iexpr(self, loopvars):
        r = self.rng
        forms = [
            lambda: str(r.randint(1, 9)),
            lambda: self.ivar(loopvars),
            lambda: "({} * {})".format(self.ivar(loopvars), r.randint(2, 5)),
            lambda: "({} % {})".format(self.ivar(loopvars), r.randint(2, 7)),
            lambda: "(acc % {})".format(r.randint(2, 13)),
            lambda: "xs[{} % 8]".format(self.ivar(loopvars)),
        ]
        # `.len()` is a call, and a call that can raise inside a try refuses
        # the whole enclosing body.
        if not self.in_try:
            forms.append(lambda: "text.len()")
        return r.choice(forms)()

    def cond(self, loopvars):
        r = self.rng
        forms = [
            lambda: "{} % {} == {}".format(self.ivar(loopvars), r.randint(2, 5),
                                           r.randint(0, 1)),
            lambda: "mode == {}".format(r.randint(0, NMODES - 1)),
            lambda: "mode >= {}".format(r.randint(1, NMODES - 1)),
            lambda: "acc % {} == 0".format(r.randint(2, 7)),
            lambda: "{} > {}".format(self.ivar(loopvars), r.randint(1, 4)),
            lambda: "slot is null",
        ]
        if "nullable" in self.features:
            forms.append(lambda: "nn is null")
        if not self.in_try:
            forms.append(lambda: "text.len() % {} == 0".format(r.randint(2, 5)))
        return r.choice(forms)()

    def warmed(self):
        """A guard that is false on the first iterations of the hot loop."""
        return "_i0 > {}".format(self.rng.randint(2, 6))

    # -- statements -------------------------------------------------------
    def safe(self, depth, loopvars, labels, ind, in_for, forced=None):
        r = self.rng
        pad = "    " * ind
        k = self.n()

        # A call inside a try refuses the whole body ("a call that can raise
        # inside a try"), and an f-string is a call, so a try body draws from a
        # narrower pool than the rest of the program.
        if self.in_try:
            pool = ["acc", "acc", "slot_set", "branch_local", "index", "div"]
            if "nullable" in self.features:
                pool += ["null_set", "null_use"]
            if depth < 3:
                pool += ["nested_for", "while_loop", "if_else"]
            if in_for:
                pool += ["break_cont"]
        else:
            pool = ["acc", "acc", "text", "slot_set", "slot_use", "slot_use",
                    "branch_local", "index", "div"]
            pool += [f for f in ("closure", "recurse", "unwind", "retkind")
                     if f in self.features]
            if "nullable" in self.features:
                pool += ["null_set", "null_use"]
            if depth < 3:
                pool += ["nested_for", "labelled", "while_loop", "if_else"]
            if in_for:
                pool += ["break_cont"]
            if depth >= 1:
                pool += ["early_return"]
        pick = forced or r.choice(pool)

        if pick == "acc":
            return ["{}acc = acc + {}".format(pad, self.iexpr(loopvars))]
        if pick == "text":
            return ['{}text = text + "{}"'.format(pad, r.choice("abcdefgh"))]
        if pick == "slot_set":
            arms = []
            for m, lit in enumerate(SLOT_ARMS, start=1):
                lit = lit.format(k=r.randint(1, 9), j=r.randint(1, 9),
                                 i=self.ivar(loopvars))
                head = "if" if m == 1 else "elif"
                arms.append("{} mode == {} {{ slot = {} }}".format(head, m, lit))
            arms.append("else {{ slot = {} }}".format(self.iexpr(loopvars)))
            return [pad + " ".join(arms)]
        if pick == "slot_use":
            return [pad + r.choice((
                'text = text + f"{slot}|"',
                "if slot is null {{ acc = acc + {} }} else {{ acc = acc + {} }}".format(
                    r.randint(1, 9), r.randint(1, 9)),
                "if slot == {} {{ acc = acc + {} }}".format(r.randint(0, 5), r.randint(1, 9)),
                "let a{}: any = slot\n{}acc = acc + a{}".format(k, pad, k),
                "let s{} = slot ?? {}\n{}text = text + f\"{{s{}}}\"".format(
                    k, r.randint(1, 9), pad, k),
            ))]
        if pick == "null_set":
            return ["{}if {} {{ nn = {} }}".format(pad, self.cond(loopvars),
                                                   self.iexpr(loopvars))]
        if pick == "null_use":
            return ["{}let v{} = nn ?? {}".format(pad, k, r.randint(1, 9)),
                    "{}acc = acc + v{}".format(pad, k)]
        if pick == "branch_local":
            return ["{}if {} {{".format(pad, self.cond(loopvars)),
                    "{}    let z{} = {}".format(pad, k, self.iexpr(loopvars)),
                    "{}    acc = acc + z{}".format(pad, k),
                    pad + "}"]
        if pick == "index":
            return [pad + r.choice((
                "acc = acc + xs[{} % 8]".format(self.ivar(loopvars)),
                "if mode == {} {{ acc = acc + xs[{}] }}".format(
                    r.randint(1, NMODES - 1), r.randint(8, 20)),
                "acc = acc + xs[-{}]".format(r.randint(1, 8)),
            ))]
        if pick == "div":
            return ["{}var den{} = {} % {} + 1".format(pad, k, self.ivar(loopvars),
                                                       r.randint(2, 5)),
                    "{}if mode == {} {{ den{} = den{} - 1 }}".format(
                        pad, r.randint(1, NMODES - 1), k, k),
                    "{}acc = acc + ({} // den{})".format(pad, r.randint(10, 99), k)]
        if pick == "closure":
            name = self.closure()
            return ["{}cap = {}".format(pad, self.iexpr(loopvars)),
                    "{}acc = acc + {}".format(pad, name)]
        if pick == "retkind":
            self.helpers.add("branchy")
            return ["{}let b{}: any = branchy({}, mode)".format(
                        pad, k, self.ivar(loopvars)),
                    '{}text = text + f"{{b{}}}"'.format(pad, k)]
        if pick == "recurse":
            which = r.choice(("rsum", "rping"))
            self.helpers.add(which)
            return ["{}acc = acc + {}({})".format(pad, which, r.randint(1, 60))]
        if pick == "unwind":
            self.helpers.add("unwind")
            return ["{}acc = acc + unwind({}, out)".format(pad, r.randint(1, 8))]
        if pick == "if_else":
            body = self.block(depth + 1, loopvars, labels, ind + 1, in_for)
            other = self.block(depth + 1, loopvars, labels, ind + 1, in_for)
            return (["{}if {} {{".format(pad, self.cond(loopvars))] + body
                    + [pad + "} else {"] + other + [pad + "}"])
        if pick == "nested_for":
            v = "_i{}".format(len(loopvars))
            body = self.block(depth + 1, loopvars + [v], labels, ind + 1, True)
            return (["{}for {} in 0..{} {{".format(pad, v, r.randint(2, 5))]
                    + body + [pad + "}"])
        if pick == "while_loop":
            v = "w{}".format(k)
            body = self.block(depth + 1, loopvars, labels, ind + 1, False)
            return (["{}var {} = 0".format(pad, v),
                     "{}while {} < {} {{".format(pad, v, r.randint(2, 5))]
                    + body + ["{}    {} = {} + 1".format(pad, v, v), pad + "}"])
        if pick == "labelled":
            lab = "L{}".format(k)
            a = "_i{}".format(len(loopvars))
            b = "_i{}".format(len(loopvars) + 1)
            inner = self.block(depth + 2, loopvars + [a, b], labels + [lab],
                               ind + 2, True)
            return (["{}'{}: for {} in 0..{} {{".format(pad, lab, a, r.randint(2, 4)),
                     "{}    for {} in 0..{} {{".format(pad, b, r.randint(2, 4))]
                    + inner
                    + ["{}        if {} {{ continue '{} }}".format(pad, self.cond(loopvars + [a, b]), lab),
                       "{}        if {} {{ break '{} }}".format(pad, self.cond(loopvars + [a, b]), lab),
                       pad + "    }", pad + "}"])
        if pick == "break_cont":
            word = r.choice(("break", "continue"))
            if labels and r.random() < 0.4:
                word += " '" + r.choice(labels)
            guard = self.cond(loopvars)
            if word.startswith("break"):
                guard = "{} and {}".format(self.warmed(), guard)
            return ["{}if {} {{ {} }}".format(pad, guard, word)]
        if pick == "early_return":
            # Guarded so it cannot fire on the first iterations: a body that
            # returns before it has done anything never gets hot, and the
            # program then compares the interpreter with itself.
            return ['{}if {} and {} {{ return f"R{}/{{acc}}/{{slot}}" }}'.format(
                pad, self.warmed(), self.cond(loopvars), k)]
        raise AssertionError(pick)

    def safe_named(self, name, depth, loopvars, labels, ind, in_for):
        return self.safe(depth, loopvars, labels, ind, in_for, forced=name)

    def stopper(self, depth, loopvars, labels, ind, in_for):
        """Constructs the tier stops the walk on. Emitted last in a block, so
        everything before them still reaches the compiled tier."""
        r = self.rng
        pad = "    " * ind
        k = self.n()
        pool = ["try_catch", "try_catch", "try_finally", "throw_prop",
                "try_return", "slot_via_catch"]
        if in_for:
            pool += ["try_break"]
        if "match" in self.features:
            pool += ["match", "match"]
        if "defer" in self.features:
            pool += ["defer", "defer_in_try"]
        pick = r.choice(pool)

        if pick == "try_catch":
            err = r.choice(ERRORS)
            self.in_try += 1
            body = self.block(depth + 1, loopvars, labels, ind + 1, False)
            self.in_try -= 1
            return ([pad + "try {"] + body
                    + ['{}    if {} {{ throw {}("t{}") }}'.format(
                        pad, self.cond(loopvars), err, k),
                       "{}    acc = acc + {}".format(pad, r.randint(1, 9)),
                       "{}}} catch _e: {} {{".format(pad, err),
                       "{}    acc = acc + {}".format(pad, r.randint(10, 40)),
                       '{}    text = text + "c"'.format(pad),
                       pad + "}"])
        if pick == "try_finally":
            err = r.choice(ERRORS)
            return ([pad + "try {",
                     '{}    if {} {{ throw {}("f{}") }}'.format(
                         pad, self.cond(loopvars), err, k),
                     "{}    acc = acc + {}".format(pad, r.randint(1, 9)),
                     "{}}} catch _e: {} {{".format(pad, err),
                     '{}    text = text + "y"'.format(pad),
                     pad + "} finally {",
                     "{}    acc = acc + {}".format(pad, r.randint(1, 5)),
                     pad + "}"])
        if pick == "slot_via_catch":
            # The handler is the only writer of the other kind, and mode 0
            # never enters it: the tier specialises `slot` to int off a warm-up
            # that never took the exception edge.
            return ([pad + "try {",
                     "{}    slot = {}".format(pad, self.iexpr(loopvars)),
                     '{}    if mode >= {} {{ throw ValueError("s{}") }}'.format(
                         pad, r.randint(1, NMODES - 1), k),
                     pad + "} catch _e: ValueError {",
                     "{}    slot = {}".format(pad, r.choice(
                         ('"c{}"'.format(k), "null", "Node({})".format(r.randint(1, 9)),
                          "[{}]".format(r.randint(1, 9)), "{}.5".format(r.randint(1, 9))))),
                     pad + "}",
                     '{}text = text + f"{{slot}}|"'.format(pad)])
        if pick == "try_break":
            # Leaving a try block sideways: the handler is never entered, but
            # the tier still has to unwind whatever the try pushed.
            word = r.choice(("break", "continue"))
            if labels and r.random() < 0.4:
                word += " '" + r.choice(labels)
            return ([pad + "try {",
                     "{}    acc = acc + {}".format(pad, r.randint(1, 9)),
                     "{}    if {} and {} {{ {} }}".format(
                         pad, self.warmed(), self.cond(loopvars), word),
                     '{}    if mode >= {} {{ throw ValueError("b{}") }}'.format(
                         pad, r.randint(1, NMODES - 1), k),
                     pad + "} catch _e: ValueError {",
                     "{}    acc = acc + {}".format(pad, r.randint(10, 40)),
                     pad + "}"])
        if pick == "try_return":
            return ([pad + "try {",
                     "{}    acc = acc + {}".format(pad, r.randint(1, 9)),
                     '{}    if {} and {} {{ return f"T{}/{{acc}}/{{slot}}" }}'.format(
                         pad, self.warmed(), self.cond(loopvars), k),
                     pad + "} finally {",
                     "{}    acc = acc + {}".format(pad, r.randint(1, 5)),
                     pad + "}"])
        if pick == "defer_in_try":
            return ([pad + "try {",
                     "{}    defer {{ out.push({}) }}".format(pad, r.randint(1, 99)),
                     "{}    acc = acc + {}".format(pad, r.randint(1, 9)),
                     '{}    if mode >= {} {{ throw ValueError("d{}") }}'.format(
                         pad, r.randint(1, NMODES - 1), k),
                     pad + "} catch _e: ValueError {",
                     "{}    acc = acc + {}".format(pad, r.randint(10, 40)),
                     pad + "}"])
        if pick == "throw_prop":
            # Never for mode 0: main warms with mode 0, and a body that raises
            # out of every warm call never compiles at all.
            return ['{}if mode >= {} {{ throw {}("p{}") }}'.format(
                pad, r.randint(1, NMODES - 1), r.choice(ERRORS), k)]
        if pick == "match":
            v = "m{}".format(k)
            arms = [r.randint(1, 9) for _ in range(5)]
            return ["{}let {} = match {} % 12 {{".format(pad, v, self.ivar(loopvars)),
                    "{}    0 => {},".format(pad, arms[0]),
                    "{}    1 | 2 => {},".format(pad, arms[1]),
                    "{}    3..=5 => {},".format(pad, arms[2]),
                    "{}    c if c >= 9 => c + {},".format(pad, arms[3]),
                    "{}    _ => {},".format(pad, arms[4]),
                    pad + "}",
                    "{}acc = acc + {}".format(pad, v)]
        if pick == "defer":
            return ["{}defer {{ out.push({}) }}".format(pad, r.randint(1, 99))]
        raise AssertionError(pick)

    def block(self, depth, loopvars, labels, ind, in_for):
        r = self.rng
        lines = []
        for _ in range(r.randint(1, 3) if depth < 3 else 1):
            lines += self.safe(depth, loopvars, labels, ind, in_for)
        # A stopper truncates the walk from where it sits, so it goes last in
        # its block and is rare below the hot loop's own body.
        if depth <= 2 and r.random() < (0.45 if depth == 1 else 0.15):
            lines += self.stopper(depth, loopvars, labels, ind, in_for)
        return lines or ["    " * ind + "acc = acc + 1"]

    def closure(self):
        """A closure defined before the hot loop and called inside it."""
        r = self.rng
        k = self.n()
        name = "f{}".format(k)
        which = r.choice(("byref", "byval", "adder"))
        if which == "byref":
            self.pre.append("    let {} = || cap * {}".format(name, r.randint(2, 5)))
            return name + "()"
        if which == "byval":
            self.pre.append("    let c{} = {}".format(k, r.randint(2, 9)))
            self.pre.append("    let {} = |x| x * c{}".format(name, k))
            return "{}(cap)".format(name)
        self.helpers.add("make_adder")
        self.pre.append("    let {} = make_adder({})".format(name, r.randint(1, 9)))
        return "{}(cap)".format(name)

    def source(self):
        r = self.rng

        # Function-level defers, and a closure list filled in the loop and
        # called after it -- the "captured a local, called later" shape.
        for _ in range(r.randint(0, 3)):
            self.pre.append("    defer {{ out.push({}) }}".format(r.randint(1, 99)))
        late = "late" in self.features
        if late:
            self.helpers.add("drain")
            self.post.append("    acc = acc + drain(fs)")

        body = self.block(1, ["_i0"], [], 2, True)
        # Every program gets one kind switch and one use of it, wherever the
        # rest of the body landed: that is the tag lie the oracle is aimed at.
        forced = (self.safe_named("slot_set", 1, ["_i0"], [], 2, True)
                  + self.safe_named("slot_use", 1, ["_i0"], [], 2, True))
        body[0:0] = forced

        if late:
            # Last, not first: OP_CLOSURE stops the walk where it sits.
            body.append("        fs.push(|| cap + {})".format(r.randint(1, 9)))

        lines = [
            "fn {}(mode: int, out: list) -> str {{".format(PROBE),
            "    var acc = 0",
            '    var text = ""',
            "    var slot: any = 0",
            "    var cap = 0",
            "    let xs = [3, 1, 4, 1, 5, 9, 2, 6]",
            "    var fs: list = []",
        ]
        if "nullable" in self.features:
            lines.insert(4, "    var nn: int? = null")
        lines += self.pre
        lines.append("    for _i0 in 0..{} {{".format(r.randint(20, 40)))
        lines += body
        lines.append("    }  # hot-loop-end")
        lines += self.post
        # `??` stops the walk (OP_JUMP_IF_NULL), so the tail read of the
        # nullable is only emitted when the program has one at all.
        nv = "-1"
        if "nullable" in self.features:
            lines.append("    let nv = nn ?? -1")
            nv = "{nv}"
        # Six parts, not nine: past some width the tier refuses the whole body
        # with "an f-string with more parts than the descriptor holds".
        lines.append('    return f"{{acc}}/{{text}}/{{slot}}/{}/{{cap}}'
                     '/{{fs.len()}}"'.format(nv))
        lines.append("}")

        helpers = "".join(HELPERS[h] for h in sorted(self.helpers))
        return (PRELUDE.format(seed=self.seed) + helpers + "\n"
                + "\n".join(lines) + "\n"
                + ATTEMPT.format(probe=PROBE, warm=WARM, modes=NMODES))


def program(seed):
    return Gen(seed).source()


# ---------------------------------------------------------------------------
# The oracle. The compiled tier may always decline, so all of these must agree
# with the interpreter, byte for byte, on stdout+stderr and on exit status.
#
# `trace` runs a copy of the program with @trace on the hot body. There is no
# env var for the function tier's threshold in this tree, and TICK_US only
# drives the OSR loop tier, so this is what reaches the FUNCTION tier early:
# @trace compiles after 8 calls instead of 64 and fills inline caches from a
# smaller observation budget, which is a different set of kind predictions to
# violate. The decorator does not change what a program prints, so the plain
# interpreter run is still the oracle for it.
CONFIGS = [
    ("interp", {"JAITHON_NO_JIT": "1"}, [], False),
    ("jit", {}, [], False),
    ("tick", {"JAITHON_JIT_TICK_US": "50"}, [], False),
    ("deopt", {"JAITHON_JIT_DEOPT_STRESS": "1"}, [], False),
    ("split", {"JAITHON_JIT_SPLIT_STRESS": "1"}, [], False),
    ("trace", {}, [], True),
    ("trace_tick", {"JAITHON_JIT_TICK_US": "50"}, [], True),
    # On by default: it is the only configuration that has found a crash here.
    # A compiled body's roots are only wrong while a collection is running, and
    # a 600-call program never allocates enough to schedule one on its own.
    ("gc", {}, ["--gc-stress=64"], False),
]


def traced(source):
    return source.replace("fn {}(".format(PROBE), "@trace\nfn {}(".format(PROBE), 1)


def run(path, env_extra, flags, timeout, why=False):
    env = dict(os.environ)
    env["JAITHON_PATH"] = os.path.join(ROOT, "lib")
    env.update(env_extra)
    if why:
        env["JAI_JIT_WHY"] = "1"
    try:
        done = subprocess.run([JAITHON, "run"] + flags + [path],
                              capture_output=True, env=env, timeout=timeout)
    except subprocess.TimeoutExpired:
        return "<timeout>", -1
    text = (done.stdout + done.stderr).decode("utf-8", "replace").strip()
    return text, done.returncode


def instructions(path, env_extra, timeout):
    """Interpreted instructions the run executed. Work the compiled tier took
    over never reaches the counter, so the drop from the interpreter's number
    is how much of the program actually ran compiled."""
    env = dict(os.environ)
    env["JAITHON_PATH"] = os.path.join(ROOT, "lib")
    env.update(env_extra)
    try:
        done = subprocess.run([JAITHON, "run", "--stats", path],
                              capture_output=True, env=env, timeout=timeout)
    except subprocess.TimeoutExpired:
        return None
    for line in (done.stdout + done.stderr).decode("utf-8", "replace").splitlines():
        if line.startswith("vm: ") and " instructions" in line:
            return int(line.split()[1])
    return None


HOT_END = "# hot-loop-end"


def loop_end_offset(path, timeout):
    """Last bytecode offset that belongs to the hot loop, from the disassembly.

    The generator tags the loop's closing brace, so the source line is known;
    disasm prints a source line beside each instruction, and the highest offset
    at or below that line is where the loop ends."""
    end_line = None
    with open(path) as f:
        for i, line in enumerate(f, start=1):
            if HOT_END in line:
                end_line = i
                break
    if end_line is None:
        return None
    env = dict(os.environ)
    env["JAITHON_PATH"] = os.path.join(ROOT, "lib")
    try:
        done = subprocess.run([JAITHON, "disasm", path],
                              capture_output=True, env=env, timeout=timeout)
    except subprocess.TimeoutExpired:
        return None
    body = False
    cur = None
    last = None
    for line in done.stdout.decode("utf-8", "replace").splitlines():
        if line.startswith("== "):
            body = line.strip() == "== {} ==".format(PROBE)
            continue
        if not body or len(line) < 10 or not line[:4].isdigit():
            continue
        off = int(line[:4])
        tag = line[4:10].strip()
        if tag.isdigit():
            cur = int(tag)
        if cur is not None and cur <= end_line:
            last = off
    return last


def compile_state(path, timeout):
    """Did the hot body reach the compiled tier, and did its LOOP compile whole?

    The OSR line is the precise signal: "osr cfprobe at N: M instructions" with
    no matching "walked only" means the loop the shapes live in ran entirely in
    the compiled tier. A walk truncated after the loop -- at OP_RUN_DEFERS, at
    the tail `??`, at the call that drains the closures -- still compiled every
    iteration, so it is not the same thing as a truncated loop."""
    text, _ = run(path, {"JAITHON_JIT_TICK_US": "50"}, [], timeout, why=True)
    reached = False
    cuts = []
    for line in text.splitlines():
        if line.startswith("[jit] compiled {} ".format(PROBE)):
            reached = True
        elif line.startswith("[jit] osr {} at".format(PROBE)) and "instructions" in line:
            reached = True
        elif line.startswith("[jit] {} walked only".format(PROBE)) or \
                (line.startswith("[jit] osr {} at".format(PROBE)) and "walked only" in line):
            tail = line.split(" at ")[-1].split(" --")[0].strip()
            if tail.isdigit():
                cuts.append(int(tail))
    if not reached:
        return "declined"
    if not cuts:
        return "full"
    end = loop_end_offset(path, timeout)
    if end is not None and min(cuts) > end:
        return "full"
    return "partial"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--count", type=int, default=200, help="programs to run")
    ap.add_argument("--seed", type=int, default=0, help="first seed")
    ap.add_argument("--timeout", type=int, default=120)
    ap.add_argument("--keep", action="store_true")
    ap.add_argument("--no-gc", action="store_true",
                    help="drop the --gc-stress configuration")
    ap.add_argument("--compile-rate", type=int, default=0, metavar="N",
                    help="generate N programs, report what fraction compiled, run none")
    args = ap.parse_args()

    if not os.access(JAITHON, os.X_OK):
        print("error: {} not built. Run 'make' first.".format(JAITHON), file=sys.stderr)
        return 2

    outdir = tempfile.mkdtemp(prefix="cffuzz-")
    configs = [c for c in CONFIGS if not (args.no_gc and c[0] == "gc")]

    if args.compile_rate:
        tally = {"full": 0, "partial": 0, "declined": 0, "rejected": 0}
        taken = []
        for seed in range(args.seed, args.seed + args.compile_rate):
            path = os.path.join(outdir, "s{}.jai".format(seed))
            with open(path, "w") as f:
                f.write(program(seed))
            text, _ = run(path, {"JAITHON_NO_JIT": "1"}, [], args.timeout)
            if "error[" in text or text == "<timeout>":
                tally["rejected"] += 1
                continue
            tally[compile_state(path, args.timeout)] += 1
            base = instructions(path, {"JAITHON_NO_JIT": "1"}, args.timeout)
            hot = instructions(path, {"JAITHON_JIT_TICK_US": "50"}, args.timeout)
            if base and hot is not None:
                taken.append(1.0 - float(hot) / base)
        total = sum(tally.values())
        ok = tally["full"] + tally["partial"]
        taken.sort()
        median = taken[len(taken) // 2] if taken else 0.0
        most = sum(1 for t in taken if t >= 0.5)
        print("control-flow fuzz compile rate: {}/{} reached the compiled tier "
              "({:.0%}), {} with the hot loop uncut, {} cut inside it, "
              "{} declined, {} rejected".format(
                  ok, total, ok / total if total else 0.0, tally["full"],
                  tally["partial"], tally["declined"], tally["rejected"]))
        print("interpreted work the tier took over: median {:.0%}, "
              "{}/{} programs over half".format(median, most, len(taken)))
        if not args.keep:
            shutil.rmtree(outdir, ignore_errors=True)
        else:
            print("programs kept in " + outdir)
        return 0

    ran = rejected = 0
    failures = []
    for seed in range(args.seed, args.seed + args.count):
        source = program(seed)
        path = os.path.join(outdir, "s{}.jai".format(seed))
        tpath = os.path.join(outdir, "t{}.jai".format(seed))
        with open(path, "w") as f:
            f.write(source)
        with open(tpath, "w") as f:
            f.write(traced(source))

        results = {}
        for name, env_extra, flags, want_trace in configs:
            results[name] = run(tpath if want_trace else path,
                                env_extra, flags, args.timeout)

        oracle, ocode = results["interp"]
        if "error[" in oracle or oracle == "<timeout>":
            rejected += 1
            continue
        ran += 1
        bad = {n: results[n] for n, _, _, _ in configs
               if n != "interp" and results[n] != (oracle, ocode)}
        if bad:
            failures.append((seed, path, (oracle, ocode), bad))

    for seed, path, oracle, got in failures:
        print("MISMATCH seed {}".format(seed))
        print("  interp: exit {} {!r}".format(oracle[1], oracle[0][:400]))
        for name, (text, code) in got.items():
            print("  {:>6}: exit {} {!r}".format(name, code, text[:400]))
        print("  program: " + path)

    print("control-flow fuzz: {} programs, {} mismatched, {} rejected "
          "(interpreter would not run them)".format(ran, len(failures), rejected))
    if failures or args.keep:
        print("programs kept in " + outdir)
    else:
        shutil.rmtree(outdir, ignore_errors=True)
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
