#!/usr/bin/env python3
"""Differential fuzzer for mutating a container while a compiled loop walks it.

The companion to kind_mutation.py. That one asks "what if the KIND changes";
this one asks "what if the CONTAINER changes". A compiled loop caches an
iterator's index, its limit, and a pointer to the backing array; the interpreter
raises when the container is mutated mid-iteration, and the compiled tier has to
raise the same thing rather than walk off the end of a reallocated array or
silently visit the wrong elements.

The guard that is supposed to catch this is `ObjList.version`, bumped on every
mutation and compared against the iterator's snapshot. `OP_FOR_ITER_BIND`'s list
arm and `OP_FOR_ITER_PAIR` both check it. This establishes that they do, for
every mutation the language offers, and that the message matches.

Each case warms the loop with a trigger that never fires so the body compiles
specialised, then calls it again with the trigger inside the loop's range.

    python3 tests/fuzz/iter_mutation.py

Exit status is non-zero if any program disagrees with the interpreter.
"""

import argparse
import os
import shutil
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
JAITHON = os.path.join(ROOT, "jaithon")

LIST_MUTATIONS = {
    "push": "xs.push(99)",
    "pop": "xs.pop()",
    "insert": "xs.insert(0, 99)",
    "remove": "xs.remove(0)",
    # Assigning in place does NOT change the size. It still has to agree with
    # the interpreter, which is the more interesting half: a version bump that
    # is too eager is a spurious raise, and one that is missing is a stale read.
    "assign": "xs[0] = 99",
}

DICT_MUTATIONS = {
    "insert": 'd["zzz"] = 99',
    "overwrite": 'd["k0"] = 99',
}

LIST_PROGRAM = """#: Generated by tests/fuzz/iter_mutation.py. Do not edit.
fn probe(xs: list, trigger: int) -> str {
    var acc = 0
    var n = 0
    for x in xs {
        acc = acc + x
        n = n + 1
        if n == trigger { MUTATION }
    }
    return f"{acc}/{n}"
}

fn attempt(xs: list, trigger: int) -> str {
    try {
        return probe(xs, trigger)
    } catch e: RuntimeError {
        return "RuntimeError"
    } catch e: ValueError {
        return "ValueError"
    } catch e: IndexError {
        return "IndexError"
    } catch e: TypeError {
        return "TypeError"
    }
}

fn main() -> int {
    var xs: list = []
    for i in 0..64 { xs.push(i) }
    var warm = ""
    #: trigger -1 never fires, so the body compiles against a loop that does
    #: not mutate. The mutation then arrives at a site already specialised.
    for _r in 0..WARM { warm = attempt(xs, -1) }
    print(warm)
    print(attempt(xs, TRIGGER))
    print(attempt(xs, TRIGGER))
    return 0
}
"""

DICT_PROGRAM = """#: Generated by tests/fuzz/iter_mutation.py. Do not edit.
fn probe(d: dict, trigger: int) -> str {
    var acc = 0
    var n = 0
    for (_k, v) in d.items() {
        acc = acc + v
        n = n + 1
        if n == trigger { MUTATION }
    }
    return f"{acc}/{n}"
}

fn attempt(d: dict, trigger: int) -> str {
    try {
        return probe(d, trigger)
    } catch e: RuntimeError {
        return "RuntimeError"
    } catch e: ValueError {
        return "ValueError"
    } catch e: IndexError {
        return "IndexError"
    } catch e: TypeError {
        return "TypeError"
    }
}

fn main() -> int {
    var d: dict = {}
    var i = 0
    while i < 64 {
        d[f"k{i}"] = i
        i = i + 1
    }
    var warm = ""
    for _r in 0..WARM { warm = attempt(d, -1) }
    print(warm)
    print(attempt(d, TRIGGER))
    print(attempt(d, TRIGGER))
    return 0
}
"""

MODES = [
    ("interp", {"JAITHON_NO_JIT": "1"}, []),
    ("jit", {}, []),
    ("deopt", {"JAITHON_JIT_DEOPT_STRESS": "1"}, []),
]


def gc_flag():
    env = dict(os.environ)
    env["JAITHON_PATH"] = os.path.join(ROOT, "lib")
    done = subprocess.run([JAITHON, "--help"], capture_output=True, env=env)
    text = (done.stdout + done.stderr).decode("utf-8", "replace")
    return "--gc-stress=64" if "--gc-stress[=N]" in text else "--gc-stress"


def run(path, env_extra, flags, timeout):
    env = dict(os.environ)
    env["JAITHON_PATH"] = os.path.join(ROOT, "lib")
    env.update(env_extra)
    try:
        done = subprocess.run([JAITHON, "run"] + flags + [path],
                              capture_output=True, env=env, timeout=timeout)
    except subprocess.TimeoutExpired:
        return "<timeout>"
    return (done.stdout + done.stderr).decode("utf-8", "replace").strip()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--warm", type=int, default=3000)
    ap.add_argument("--timeout", type=int, default=120)
    ap.add_argument("--keep", action="store_true")
    args = ap.parse_args()

    if not os.access(JAITHON, os.X_OK):
        print(f"error: {JAITHON} not built. Run 'make' first.", file=sys.stderr)
        return 2

    modes = MODES + [("gc", {}, [gc_flag()])]
    outdir = tempfile.mkdtemp(prefix="itermut-")
    cases = []
    # Triggers: first element, mid-walk, and the last one -- the boundary where
    # a stale limit and a fresh one disagree by exactly one.
    for trigger in (1, 30, 64):
        for name, mutation in LIST_MUTATIONS.items():
            cases.append((f"list-{name}-at{trigger}", LIST_PROGRAM, mutation, trigger))
        for name, mutation in DICT_MUTATIONS.items():
            cases.append((f"dict-{name}-at{trigger}", DICT_PROGRAM, mutation, trigger))

    ran = skipped = 0
    failures = []
    for name, template, mutation, trigger in cases:
        path = os.path.join(outdir, name.replace("-", "_") + ".jai")
        with open(path, "w") as f:
            f.write(template
                    .replace("MUTATION", mutation)
                    .replace("TRIGGER", str(trigger))
                    .replace("WARM", str(args.warm)))
        results = {m: run(path, e, fl, args.timeout) for m, e, fl in modes}
        if "error[" in results["interp"] or results["interp"] == "<timeout>":
            skipped += 1
            continue
        ran += 1
        oracle = results["interp"]
        bad = {m: results[m] for m in ("jit", "deopt", "gc") if results[m] != oracle}
        if bad:
            failures.append((name, path, oracle, bad))

    for name, path, oracle, got in failures:
        print(f"MISMATCH {name}")
        print(f"  interp: {oracle!r}")
        for mode, value in got.items():
            print(f"  {mode:>6}: {value!r}")
        print(f"  program: {path}")

    print(f"iter-mutation fuzz: {ran} cases, {len(failures)} mismatched, "
          f"{skipped} skipped (interpreter rejected)")
    if not failures and not args.keep:
        shutil.rmtree(outdir, ignore_errors=True)
    elif failures:
        print(f"generated programs kept in {outdir}")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
