#!/usr/bin/env python3
"""Differential fuzzer for kind stability in the compiled tier.

Both silent miscompiles found on 2026-08-12 had the same shape: the tier samples
a value's kind while a loop is warming, specialises the compiled body to it, and
the program then puts a different kind there. The compiled code read the new
value's payload under the old value's tag.

  - a `str` in a list sampled as int bound the string's POINTER as an integer
    (41080394656 where the interpreter raises TypeError)
  - a `bool` local at an OSR entry was read eight bytes wide, so `if flag {`
    took the wrong arm

Neither was caught by anything. This generates the whole matrix -- container and
field shapes x the kind that arrives late x what the body does with it -- runs
each program four ways, and diffs. The interpreter is the oracle; the compiled
tier must either agree with it or deopt to it.

    python3 tests/fuzz/kind_mutation.py            # the standard matrix
    python3 tests/fuzz/kind_mutation.py --keep     # leave the .jai files behind
    python3 tests/fuzz/kind_mutation.py --warm 20000

Exit status is non-zero if any program disagrees, so it can be a gate.
"""

import argparse
import os
import shutil
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
JAITHON = os.path.join(ROOT, "jaithon")

# A literal per kind. `late` is what arrives after the loop has compiled.
KINDS = {
    "int": "7",
    "float": "0.5",
    "bool": "true",
    "str": '"s"',
    "null": "null",
    "list": "[1, 2]",
    "inst": "Holder(3)",
}

# What the loop body does with the element. Each must be legal for an int and
# must produce a DIFFERENT observable answer if the element is read as the wrong
# kind -- a body that ignores its element proves nothing.
CONSUMERS = {
    # Arithmetic: a wrong tag shows up as a wrong number or a missing raise.
    "add": "acc = acc + x",
    # Formatting: routes through the value's own printing, so a pointer read as
    # an int is visible even when arithmetic would have raised.
    "fmt": 'text = text + f"{x}|"',
    # Comparison: exercises the compare arms rather than the arithmetic ones.
    "cmp": "if x == 7 { acc = acc + 1 }",
}

PRELUDE = """#: Generated by tests/fuzz/kind_mutation.py. Do not edit.
class Holder {
    pub var n: int
    fn init(self, n: int) { self.n = n }
}

class Box {
    pub var slot: any
    fn init(self, slot: any) { self.slot = slot }
}
"""

# Each shape warms a loop over 64 same-kind elements, then the caller puts a
# different kind in and calls again. `body` is spliced with the consumer.
SHAPES = {
    # `for x in xs` -- OP_FOR_ITER_BIND's list arm, where the pointer-as-int bug was.
    "list_for": """
fn probe(xs: list) -> str {
    var acc = 0
    var text = ""
    for x in xs { CONSUMER }
    return f"{acc}/{text.len()}"
}
""",
    # `xs[i]` -- OP_GET_INDEX rather than the iterator.
    "list_index": """
fn probe(xs: list) -> str {
    var acc = 0
    var text = ""
    var i = 0
    while i < xs.len() {
        let x = xs[i]
        CONSUMER
        i = i + 1
    }
    return f"{acc}/{text.len()}"
}
""",
    # A field of declared type `any` read in a loop -- OP_GET_FIELD_LOCAL.
    "field": """
fn probe(xs: list) -> str {
    var acc = 0
    var text = ""
    for b in xs {
        let x = b.slot
        CONSUMER
    }
    return f"{acc}/{text.len()}"
}
""",
    # A dict value -- the OP_FOR_ITER_PAIR path.
    "dict_pair": """
fn probe(d: dict) -> str {
    var acc = 0
    var text = ""
    for (_k, x) in d.items() { CONSUMER }
    return f"{acc}/{text.len()}"
}
""",
}

# How main builds the container for each shape, warms it, then mutates it.
BUILDERS = {
    "list_for": """
fn main() -> int {
    var xs: list = []
    for _i in 0..64 { xs.push(EARLY) }
    var warm = ""
    for _r in 0..WARM { warm = attempt(xs) }
    print(warm)
    xs.push(LATE)
    print(attempt(xs))
    print(attempt(xs))
    return 0
}
""",
    "list_index": """
fn main() -> int {
    var xs: list = []
    for _i in 0..64 { xs.push(EARLY) }
    var warm = ""
    for _r in 0..WARM { warm = attempt(xs) }
    print(warm)
    xs.push(LATE)
    print(attempt(xs))
    print(attempt(xs))
    return 0
}
""",
    "field": """
fn main() -> int {
    var xs: list = []
    for _i in 0..64 { xs.push(Box(EARLY)) }
    var warm = ""
    for _r in 0..WARM { warm = attempt(xs) }
    print(warm)
    xs.push(Box(LATE))
    print(attempt(xs))
    print(attempt(xs))
    return 0
}
""",
    "dict_pair": """
fn main() -> int {
    var d: dict = {}
    var i = 0
    while i < 64 {
        d[f"k{i}"] = EARLY
        i = i + 1
    }
    var warm = ""
    for _r in 0..WARM { warm = attempt(d) }
    print(warm)
    d["late"] = LATE
    print(attempt(d))
    print(attempt(d))
    return 0
}
""",
}

ATTEMPT = """
#: Every wrong-kind outcome the interpreter can produce is a raise, so both
#: sides have to be able to print one. Anything that is NOT a raise and NOT the
#: interpreter's number is a miscompile.
fn attempt(c: any) -> str {
    try {
        return probe(c)
    } catch e: TypeError {
        return "TypeError"
    } catch e: ValueError {
        return "ValueError"
    }
}
"""


def program(shape, consumer, early, late, warm):
    body = SHAPES[shape].replace("CONSUMER", CONSUMERS[consumer])
    main = (BUILDERS[shape]
            .replace("EARLY", KINDS[early])
            .replace("LATE", KINDS[late])
            .replace("WARM", str(warm)))
    return PRELUDE + body + ATTEMPT + main


def gc_flag():
    """`--gc-stress=N` postdates this fuzzer's first use.

    Probing for it means the fuzzer can be pointed at an OLDER binary, which is
    the only way to prove it has teeth: build the tree from before a fix, run
    the matrix, and watch the cases that fix addressed light up. Without this
    every case "fails" on a CLI usage error and the signal is lost in it.
    """
    env = dict(os.environ)
    env["JAITHON_PATH"] = os.path.join(ROOT, "lib")
    done = subprocess.run([JAITHON, "--help"], capture_output=True, env=env)
    text = (done.stdout + done.stderr).decode("utf-8", "replace")
    return "--gc-stress[=N]" in text and "--gc-stress=64" or "--gc-stress"


MODES = [
    ("interp", {"JAITHON_NO_JIT": "1"}, []),
    ("jit", {}, []),
    ("deopt", {"JAITHON_JIT_DEOPT_STRESS": "1"}, []),
    ("gc", {}, [gc_flag()]),
]


def run(path, env_extra, flags, timeout):
    env = dict(os.environ)
    env["JAITHON_PATH"] = os.path.join(ROOT, "lib")
    env.update(env_extra)
    try:
        done = subprocess.run([JAITHON, "run"] + flags + [path],
                              capture_output=True, env=env, timeout=timeout)
    except subprocess.TimeoutExpired:
        return "<timeout>"
    return (done.stdout + done.stderr).decode("utf-8", "replace").strip()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--warm", type=int, default=8000,
                    help="loop repetitions before the kind changes")
    ap.add_argument("--timeout", type=int, default=120)
    ap.add_argument("--keep", action="store_true",
                    help="keep generated .jai files for inspection")
    ap.add_argument("--filter", default="",
                    help="only run cases whose name contains this")
    args = ap.parse_args()

    if not os.access(JAITHON, os.X_OK):
        print(f"error: {JAITHON} not built. Run 'make' first.", file=sys.stderr)
        return 2

    cases = []
    for shape in SHAPES:
        for consumer in CONSUMERS:
            for early in ("int", "float"):
                for late in KINDS:
                    if late == early:
                        continue
                    cases.append((shape, consumer, early, late))

    outdir = tempfile.mkdtemp(prefix="kindfuzz-")
    ran = skipped = 0
    failures = []

    for shape, consumer, early, late in cases:
        name = f"{shape}-{consumer}-{early}-to-{late}"
        if args.filter and args.filter not in name:
            continue
        path = os.path.join(outdir, name.replace("-", "_") + ".jai")
        with open(path, "w") as f:
            f.write(program(shape, consumer, early, late, args.warm))

        results = {}
        for mode, env_extra, flags in MODES:
            results[mode] = run(path, env_extra, flags, args.timeout)

        # A program the interpreter itself cannot run is a bad generator case,
        # not a finding -- report it as skipped rather than pretending it passed.
        if "error[" in results["interp"] or results["interp"] == "<timeout>":
            skipped += 1
            continue

        ran += 1
        oracle = results["interp"]
        bad = [m for m in ("jit", "deopt", "gc") if results[m] != oracle]
        if bad:
            failures.append((name, path, oracle, {m: results[m] for m in bad}))

    for name, path, oracle, got in failures:
        print(f"MISMATCH {name}")
        print(f"  interp: {oracle!r}")
        for mode, value in got.items():
            print(f"  {mode:>6}: {value!r}")
        print(f"  program: {path}")

    print(f"kind-mutation fuzz: {ran} cases, {len(failures)} mismatched, "
          f"{skipped} skipped (interpreter rejected)")
    if not failures and not args.keep:
        # rmtree, not unlink: running a program leaves a __jaicache__ DIRECTORY
        # next to it.
        shutil.rmtree(outdir, ignore_errors=True)
    elif failures:
        print(f"generated programs kept in {outdir}")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
