#!/usr/bin/env python3
"""Differential fuzzer for kind stability in the compiled tier.

Both silent miscompiles found on 2026-08-12 had the same shape: the tier samples
a value's kind while a loop is warming, specialises the compiled body to it, and
the program then puts a different kind there. The compiled code read the new
value's payload under the old value's tag.

  - a `str` in a list sampled as int bound the string's POINTER as an integer
    (41080394656 where the interpreter raises TypeError)
  - a `bool` local at an OSR entry was read eight bytes wide, so `if flag {`
    took the wrong arm

Neither was caught by anything. This generates the whole matrix -- container and
field shapes x the kind that arrives late x what the body does with it -- runs
each program four ways, and diffs. The interpreter is the oracle; the compiled
tier must either agree with it or deopt to it.

A second family (DYN_SHAPES, further down) does the same for a local written
with two different kinds in one body -- a "dynamic local", which is stored in
the frame behind a runtime tag and read through `localIn`'s guard block. Three
more confirmed miscompiles lived there, and nothing the matrix above generates
reaches it, since every shape there writes each local exactly once.

    python3 tests/fuzz/kind_mutation.py            # the standard matrix
    python3 tests/fuzz/kind_mutation.py --keep     # leave the .jai files behind
    python3 tests/fuzz/kind_mutation.py --warm 20000

Exit status is non-zero if any program disagrees, so it can be a gate.
"""

import argparse
import os
import shutil
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
JAITHON = os.path.join(ROOT, "jaithon")

# A literal per kind. `late` is what arrives after the loop has compiled.
KINDS = {
    "int": "7",
    "float": "0.5",
    "bool": "true",
    "str": '"s"',
    "null": "null",
    "list": "[1, 2]",
    "inst": "Holder(3)",
}

# What the loop body does with the element. Each must be legal for an int and
# must produce a DIFFERENT observable answer if the element is read as the wrong
# kind -- a body that ignores its element proves nothing.
CONSUMERS = {
    # Arithmetic: a wrong tag shows up as a wrong number or a missing raise.
    "add": "acc = acc + x",
    # Formatting: routes through the value's own printing, so a pointer read as
    # an int is visible even when arithmetic would have raised.
    "fmt": 'text = text + f"{x}|"',
    # Comparison: exercises the compare arms rather than the arithmetic ones.
    "cmp": "if x == 7 { acc = acc + 1 }",
    # `x.n` -- legal only when `x` is compiled as an instance, which is what
    # gives OP_GET_INDEX's own SLOT_INST arm (and its Obj.type/shape guard)
    # something to run at all. `add`/`fmt`/`cmp` never do: the compiler
    # observes an instance-kinded element and declines the arithmetic/compare
    # opcode outright ("OP_ADD_LOCALS" etc.), so `probe` never compiles and
    # the case passes on zero coverage -- see CONSUMER_KINDS below.
    "inst_field": "acc = acc + x.n",
    # `x.len()` -- legal only when `x` is compiled as a list, for the same
    # reason: it is what exercises OP_GET_INDEX's SLOT_LIST arm.
    "obj_len": "acc = acc + x.len()",
}

# Which EARLY kinds a consumer actually compiles for. The compiled body is
# specialised to what the EARLY samples look like (the LATE sample is the one
# that arrives after compilation and is meant to violate the specialisation),
# so a consumer paired with an EARLY kind it cannot compile for isn't a
# mismatch case at all -- `probe` just declines, both modes run interpreted,
# outputs trivially agree, and the case "passes" having exercised nothing.
# Confirmed by hand: `add`/`fmt`/`cmp` decline outright for `early="inst"` or
# `early="list"` (OP_ADD_LOCALS, an add-bind of a kind that is neither int nor
# float, OP_JUMP_IF_CMP_LOCAL_K); `inst_field`/`obj_len` are the inverse, they
# need the object kind to resolve `.n`/`.len()` at all. Absent from this table
# defaults to the original ("int", "float").
CONSUMER_KINDS = {
    "inst_field": ("inst",),
    "obj_len": ("list",),
}

# Shapes where EARLY/LATE is the element itself (`for x in xs` / `xs[i]`),
# which is what the two OP_GET_INDEX bugs this fuzzer was meant to catch (and
# didn't) actually needed. The other seven shapes wrap the element in
# something else first (a field, a tuple slot, a dict value, a closure
# upvalue, a global, a method receiver, a return value) and have not been
# verified to compile with the object-kind consumers above -- widening them
# needs their own wrapper varied too, not just EARLY/LATE, so it is left for
# a dedicated pass rather than guessed here.
OBJECT_CONSUMER_SHAPES = ("list_for", "list_index")

PRELUDE = """#: Generated by tests/fuzz/kind_mutation.py. Do not edit.
var gslot: any = 0

class Early {
    pub var v: any
    fn init(self, v: any) { self.v = v }
    pub fn get(self) -> any { return self.v }
}

class Late {
    pub var v: any
    fn init(self, v: any) { self.v = v }
    pub fn get(self) -> any { return self.v }
}

class Holder {
    pub var n: int
    fn init(self, n: int) { self.n = n }
}

class Box {
    pub var slot: any
    fn init(self, slot: any) { self.slot = slot }
}
"""

# Each shape warms a loop over 64 same-kind elements, then the caller puts a
# different kind in and calls again. `body` is spliced with the consumer.
SHAPES = {
    # `for x in xs` -- OP_FOR_ITER_BIND's list arm, where the pointer-as-int bug was.
    "list_for": """
fn probe(xs: list) -> str {
    var acc = 0
    var text = ""
    for x in xs { CONSUMER }
    return f"{acc}/{text.len()}"
}
""",
    # `xs[i]` -- OP_GET_INDEX rather than the iterator.
    "list_index": """
fn probe(xs: list) -> str {
    var acc = 0
    var text = ""
    var i = 0
    while i < xs.len() {
        let x = xs[i]
        CONSUMER
        i = i + 1
    }
    return f"{acc}/{text.len()}"
}
""",
    # A field of declared type `any` read in a loop -- OP_GET_FIELD_LOCAL.
    "field": """
fn probe(xs: list) -> str {
    var acc = 0
    var text = ""
    for b in xs {
        let x = b.slot
        CONSUMER
    }
    return f"{acc}/{text.len()}"
}
""",
    # A dict value -- the OP_FOR_ITER_PAIR path.
    "dict_pair": """
fn probe(d: dict) -> str {
    var acc = 0
    var text = ""
    for (_k, x) in d.items() { CONSUMER }
    return f"{acc}/{text.len()}"
}
""",
    # A tuple element. Fixed-size and hashable, so a different arm than a list.
    "tuple_elem": """
fn probe(xs: list) -> str {
    var acc = 0
    var text = ""
    for t in xs {
        let x = t[1]
        CONSUMER
    }
    return f"{acc}/{text.len()}"
}
""",
    # A closure upvalue read through the closure. `cur` is a `var`, so it is
    # captured BY REFERENCE -- the compiled body specialises to the kind it was
    # holding, and the loop then puts a different one there.
    "upvalue": """
fn probe(xs: list) -> str {
    var acc = 0
    var text = ""
    var cur: any = 0
    let peek = || cur
    for e in xs {
        cur = e
        let x = peek()
        CONSUMER
    }
    return f"{acc}/{text.len()}"
}
""",
    # A module-level `var`, written and read back inside the compiled body.
    "global": """
fn probe(xs: list) -> str {
    var acc = 0
    var text = ""
    for e in xs {
        gslot = e
        let x = gslot
        CONSUMER
    }
    return f"{acc}/{text.len()}"
}
""",
    # The RECEIVER's class changes, not just the value's kind: the same method
    # name on two unrelated classes, which is what an inline cache caches.
    "recv_class": """
fn probe(xs: list) -> str {
    var acc = 0
    var text = ""
    for r in xs {
        let x = r.get()
        CONSUMER
    }
    return f"{acc}/{text.len()}"
}
""",
    # A function whose RETURN kind changes. Roadmap section 6: a prediction
    # recorded at inline-cache fill is a first observation.
    "return_kind": """
fn source(v: any, flip: bool) -> any {
    if flip { return v }
    return 1
}

fn probe(xs: list) -> str {
    var acc = 0
    var text = ""
    for e in xs {
        let x = source(e, true)
        CONSUMER
    }
    return f"{acc}/{text.len()}"
}
""",
}

# How main builds the container for each shape, warms it, then mutates it.
BUILDERS = {
    "list_for": """
fn main() -> int {
    var xs: list = []
    for _i in 0..64 { xs.push(EARLY) }
    var warm = ""
    for _r in 0..WARM { warm = attempt(xs) }
    print(warm)
    xs.push(LATE)
    print(attempt(xs))
    print(attempt(xs))
    return 0
}
""",
    "list_index": """
fn main() -> int {
    var xs: list = []
    for _i in 0..64 { xs.push(EARLY) }
    var warm = ""
    for _r in 0..WARM { warm = attempt(xs) }
    print(warm)
    xs.push(LATE)
    print(attempt(xs))
    print(attempt(xs))
    return 0
}
""",
    "field": """
fn main() -> int {
    var xs: list = []
    for _i in 0..64 { xs.push(Box(EARLY)) }
    var warm = ""
    for _r in 0..WARM { warm = attempt(xs) }
    print(warm)
    xs.push(Box(LATE))
    print(attempt(xs))
    print(attempt(xs))
    return 0
}
""",
    "dict_pair": """
fn main() -> int {
    var d: dict = {}
    var i = 0
    while i < 64 {
        d[f"k{i}"] = EARLY
        i = i + 1
    }
    var warm = ""
    for _r in 0..WARM { warm = attempt(d) }
    print(warm)
    d["late"] = LATE
    print(attempt(d))
    print(attempt(d))
    return 0
}
""",
    "tuple_elem": """
fn main() -> int {
    var xs: list = []
    for _i in 0..64 { xs.push((0, EARLY)) }
    var warm = ""
    for _r in 0..WARM { warm = attempt(xs) }
    print(warm)
    xs.push((0, LATE))
    print(attempt(xs))
    print(attempt(xs))
    return 0
}
""",
    "upvalue": """
fn main() -> int {
    var xs: list = []
    for _i in 0..64 { xs.push(EARLY) }
    var warm = ""
    for _r in 0..WARM { warm = attempt(xs) }
    print(warm)
    xs.push(LATE)
    print(attempt(xs))
    print(attempt(xs))
    return 0
}
""",
    "global": """
fn main() -> int {
    var xs: list = []
    for _i in 0..64 { xs.push(EARLY) }
    var warm = ""
    for _r in 0..WARM { warm = attempt(xs) }
    print(warm)
    xs.push(LATE)
    print(attempt(xs))
    print(attempt(xs))
    return 0
}
""",
    "recv_class": """
fn main() -> int {
    var xs: list = []
    for _i in 0..64 { xs.push(Early(EARLY)) }
    var warm = ""
    for _r in 0..WARM { warm = attempt(xs) }
    print(warm)
    xs.push(Late(LATE))
    print(attempt(xs))
    print(attempt(xs))
    return 0
}
""",
    "return_kind": """
fn main() -> int {
    var xs: list = []
    for _i in 0..64 { xs.push(EARLY) }
    var warm = ""
    for _r in 0..WARM { warm = attempt(xs) }
    print(warm)
    xs.push(LATE)
    print(attempt(xs))
    print(attempt(xs))
    return 0
}
""",
}

# ---------------------------------------------------------------------------
# Dynamic locals.
#
# Every shape above writes each local ONCE, from one source, so no program the
# matrix generates has ever produced what the tier calls a "dynamic local": a
# single slot written with two different kinds at two points in one body. That
# forces the slot out of a register into frame memory behind a runtime type tag
# (`dynamicLocal[slot]`), and routes every read of it through `localIn`'s guard
# block in src/vm/jit/jit_func.c. Three of the confirmed miscompiles this
# fuzzer exists to catch lived in exactly that block -- SLOT_LIST, SLOT_INST
# and SLOT_MAYBE_INST dynamic locals, all three cases of `localTagFor` mapping
# distinct object kinds onto the same VAL_OBJ tag -- and the matrix above
# cannot reach it however EARLY/LATE are tuned, because it never writes one
# local twice.
#
# This is a separate generation path rather than more SHAPES rows because the
# shape genuinely differs: two writes instead of one, self-recursion in two of
# them, and the thing whose kind changes is an ARGUMENT rather than an element
# of a container. The bodies are copied structurally from
# tests/golden/jit_dynamic_local_{list,inst,maybe_inst}.jai -- the regression
# tests for those three bugs -- rather than invented, and each one's compiled
# `insts` matches its golden's exactly (284/668/2048/2512), which is the check
# that the copy kept the property that mattered.
DYN_PRELUDE = """#: Generated by tests/fuzz/kind_mutation.py. Do not edit.
#: `Dog.legs` and `Bird.wings` share a byte offset, and `Bird` has its own
#: `legs` at a different one: reading a Bird through Dog's layout yields 99
#: rather than 2, so a missed class guard is a wrong NUMBER, not a raise.
#: `Cat` is the same trap one step further out -- it has `legs` too, at yet
#: another offset -- so it stays a wrong number even for the late mutation.
class Dog {
    pub var legs: int = 4
    pub var link: any = null
}

class Bird {
    pub var wings: int = 99
    pub var legs: int = 2
}

class Cat {
    pub var tail: int = 1
    pub var whiskers: int = 12
    pub var legs: int = 77
}

class Holder {
    pub var n: int
    fn init(self, n: int) { self.n = n }
}
"""

# Bodies. `seed` and `other` are written to the SAME local, which is what makes
# it dynamic; the read sits between the two writes so it sees both kinds.
DYN_SHAPES = {
    # jit_dynamic_local_list.jai: a SLOT_LIST dynamic local. The read is
    # compiled for the list `seed`, and the dict `other` shares its VAL_OBJ tag.
    "dyn_index": """
fn probe(seed: any, n: int, other: any) -> int {
    var a = seed
    var t = 0
    var i = 0
    while i < n {
        t = t + a[0]
        a = other
        i = i + 1
    }
    return t
}
""",
    # jit_dynamic_local_inst.jai: a SLOT_INST dynamic local, where the guard
    # has to confirm the CLASS and not just `Obj.type == OBJ_INSTANCE`.
    "dyn_field": """
fn probe(seed: any, n: int, other: any) -> int {
    var a = seed
    var t = 0
    var i = 0
    while i < n {
        t = a.legs + t
        a = other
        i = i + 1
    }
    return t
}
""",
    # jit_dynamic_local_maybe_inst.jai's `plain`: binding a nullable instance
    # FIELD (`seed.link`, a Dog or null) gives the slot SLOT_MAYBE_INST, whose
    # tag is that same VAL_OBJ. One compile retry, no recursion.
    #
    # `a.legs + t`, not `t + a.legs`: the second order emits a bare
    # OP_GET_FIELD, which the tier declines outright -- `probe` then never
    # compiles, both modes run interpreted, and the case passes having tested
    # nothing. Verified by hand with JAI_JIT_WHY=1, and the same silent-decline
    # trap CONSUMER_KINDS above exists to prevent.
    "dyn_maybe": """
fn probe(seed: any, n: int, other: any) -> int {
    var a = seed.link
    var t = 0
    var i = 0
    while i < n {
        t = a.legs + t
        a = other
        i = i + 1
    }
    return t
}
""",
    # jit_dynamic_local_maybe_inst.jai's `nullable`: the parameter route to the
    # same kind, which is set on a different compile pass than `dyn_maybe`'s
    # and so needs its own case. The self-call passes `a.link` (a Dog or null)
    # back into the parameter slot, flagging it nullable on one retry, while
    # `a = other` flags the same slot dynamic on another; the merge step never
    # clears the first, so both arrive set. `i > 100` never fires at n=3 -- the
    # recursion only has to be COMPILED, not run. The trailing `a = c` restores
    # the seed's class so the entry contract still accepts a Dog.
    "rec_nullable": """
fn probe(a: any, n: int, other: any) -> int {
    var c = a
    var t = 0
    var i = 0
    while i < n {
        t = a.legs + t
        if i > 100 {
            var q = a.link
            t = t + probe(q, 0, other)
        }
        a = other
        i = i + 1
    }
    a = c
    return t
}
""",
    # jit_dynamic_local_maybe_inst.jai's `checked`: `rec_nullable` plus the
    # explicit null tests, which is what reaches the OTHER bug in that file --
    # the prologue seeding a spilled SLOT_MAYBE_INST parameter with a
    # compile-time constant tag, so a literal `null` argument landed in the
    # frame as OBJ_VAL(NULL) and `a == null` read false over it. Reached by the
    # direct `probe(null, ...)` call in DYN_EXTRA, not by the self-call.
    "rec_checked": """
fn probe(a: any, n: int, other: any) -> int {
    var c = a
    var t = 0
    var i = 0
    while i < n {
        if a == null { return -1 }
        t = a.legs + t
        if i > 100 {
            var q = a.link
            t = t + probe(q, 0, other)
        }
        a = other
        i = i + 1
    }
    a = c
    if a == null { return -2 }
    return t
}
""",
}

# The seed, and the second warm-up kind that makes the slot dynamic. Both are
# held FIXED at the pairing its golden confirmed a real miscompile with -- that
# pairing is what decides which SlotKind the read compiles for, and varying it
# too would multiply the matrix for shapes whose guard is the same code.
DYN_SEEDS = {
    "dyn_index": "    let seed: any = [10, 20, 30]\n",
    "dyn_field": "    let seed: any = Dog()\n",
    "dyn_maybe": "    let seed: any = Dog()\n    seed.link = Dog()\n",
    "rec_nullable": "    let seed: any = Dog()\n    seed.link = Dog()\n",
    "rec_checked": "    let seed: any = Dog()\n    seed.link = Dog()\n",
}
DYN_MIDS = {
    "dyn_index": "{0: 99}",
    "dyn_field": "Bird()",
    "dyn_maybe": "Bird()",
    "rec_nullable": "Bird()",
    "rec_checked": "Bird()",
}
DYN_EXTRA = {"rec_checked": "    print(attempt(null, 3, late))\n"}

# What arrives in the dynamic slot once the body is compiled. A superset of
# KINDS: `dict` and the two extra classes exist because the bugs here were all
# object kinds colliding under one value tag, so the object side is where the
# resolution has to be finest. `inst_nofield` has neither `legs` nor an index
# (the interpreter raises, and a missed guard shows up as a number instead);
# `inst_offset` has `legs` at a third offset, so both sides return a number and
# only the VALUE separates them.
DYN_LATE = {
    "int": "7",
    "float": "0.5",
    "bool": "true",
    "str": '"s"',
    "null": "null",
    "list": "[10, 20, 30]",
    "dict": "{0: 99}",
    "inst_nofield": "Holder(3)",
    "inst_offset": "Cat()",
}

DYN_ATTEMPT = """
fn attempt(seed: any, n: int, other: any) -> str {
    try {
        return f"{probe(seed, n, other)}"
    } catch e: TypeError {
        return "TypeError"
    } catch e: ValueError {
        return "ValueError"
    } catch e: Error {
        return "Error"
    }
}
"""

DYN_MAIN = """
fn main() -> int {
SEED    let mid: any = MID
    let late: any = LATE
    var warm = ""
    for _r in 0..WARM { warm = attempt(seed, 3, mid) }
    print(warm)
    print(attempt(seed, 3, late))
    print(attempt(seed, 3, late))
EXTRA    return 0
}
"""

ATTEMPT = """
#: Every wrong-kind outcome the interpreter can produce is a raise, so both
#: sides have to be able to print one. Anything that is NOT a raise and NOT the
#: interpreter's number is a miscompile.
#:
#: The base `Error` catch is required once a consumer can raise something
#: other than TypeError/ValueError -- `x.n`/`x.len()` on a value that has
#: neither raises AttributeError, and an uncaught raise here does not just
#: mis-score one case, it aborts `main()` on the FIRST attempt() call that
#: hits it, so the second and third calls (the ones actually holding the
#: mutated LATE kind) never run at all and the case silently loses coverage
#: rather than failing loudly.
fn attempt(c: any) -> str {
    try {
        return probe(c)
    } catch e: TypeError {
        return "TypeError"
    } catch e: ValueError {
        return "ValueError"
    } catch e: Error {
        return "Error"
    }
}
"""


def program(shape, consumer, early, late, warm):
    body = SHAPES[shape].replace("CONSUMER", CONSUMERS[consumer])
    main = (BUILDERS[shape]
            .replace("EARLY", KINDS[early])
            .replace("LATE", KINDS[late])
            .replace("WARM", str(warm)))
    return PRELUDE + body + ATTEMPT + main


def dyn_program(shape, late, warm):
    main = (DYN_MAIN
            .replace("SEED", DYN_SEEDS[shape])
            .replace("MID", DYN_MIDS[shape])
            .replace("LATE", DYN_LATE[late])
            .replace("WARM", str(warm))
            .replace("EXTRA", DYN_EXTRA.get(shape, "")))
    return DYN_PRELUDE + DYN_SHAPES[shape] + DYN_ATTEMPT + main


def gc_flag():
    """`--gc-stress=N` postdates this fuzzer's first use.

    Probing for it means the fuzzer can be pointed at an OLDER binary, which is
    the only way to prove it has teeth: build the tree from before a fix, run
    the matrix, and watch the cases that fix addressed light up. Without this
    every case "fails" on a CLI usage error and the signal is lost in it.
    """
    env = dict(os.environ)
    env["JAITHON_PATH"] = os.path.join(ROOT, "lib")
    done = subprocess.run([JAITHON, "--help"], capture_output=True, env=env)
    text = (done.stdout + done.stderr).decode("utf-8", "replace")
    return "--gc-stress[=N]" in text and "--gc-stress=64" or "--gc-stress"


MODES = [
    ("interp", {"JAITHON_NO_JIT": "1"}, []),
    ("jit", {}, []),
    ("deopt", {"JAITHON_JIT_DEOPT_STRESS": "1"}, []),
    ("gc", {}, [gc_flag()]),
]


def run(path, env_extra, flags, timeout):
    env = dict(os.environ)
    env["JAITHON_PATH"] = os.path.join(ROOT, "lib")
    env.update(env_extra)
    try:
        done = subprocess.run([JAITHON, "run"] + flags + [path],
                              capture_output=True, env=env, timeout=timeout)
    except subprocess.TimeoutExpired:
        return "<timeout>"
    return (done.stdout + done.stderr).decode("utf-8", "replace").strip()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--warm", type=int, default=8000,
                    help="loop repetitions before the kind changes")
    ap.add_argument("--timeout", type=int, default=120)
    ap.add_argument("--keep", action="store_true",
                    help="keep generated .jai files for inspection")
    ap.add_argument("--filter", default="",
                    help="only run cases whose name contains this")
    args = ap.parse_args()

    if not os.access(JAITHON, os.X_OK):
        print(f"error: {JAITHON} not built. Run 'make' first.", file=sys.stderr)
        return 2

    # (name, source). Both families land in one list so the run loop, the
    # --filter and the reporting stay single-path.
    cases = []
    for shape in SHAPES:
        for consumer in CONSUMERS:
            if consumer in CONSUMER_KINDS and shape not in OBJECT_CONSUMER_SHAPES:
                continue
            for early in CONSUMER_KINDS.get(consumer, ("int", "float")):
                for late in KINDS:
                    if late == early:
                        continue
                    cases.append((f"{shape}-{consumer}-{early}-to-{late}",
                                  program(shape, consumer, early, late, args.warm)))
    for shape in DYN_SHAPES:
        for late in DYN_LATE:
            cases.append((f"{shape}-to-{late}",
                          dyn_program(shape, late, args.warm)))

    outdir = tempfile.mkdtemp(prefix="kindfuzz-")
    ran = skipped = 0
    failures = []

    for name, source in cases:
        if args.filter and args.filter not in name:
            continue
        path = os.path.join(outdir, name.replace("-", "_") + ".jai")
        with open(path, "w") as f:
            f.write(source)

        results = {}
        for mode, env_extra, flags in MODES:
            results[mode] = run(path, env_extra, flags, args.timeout)

        # A program the interpreter itself cannot run is a bad generator case,
        # not a finding -- report it as skipped rather than pretending it passed.
        if "error[" in results["interp"] or results["interp"] == "<timeout>":
            skipped += 1
            continue

        ran += 1
        oracle = results["interp"]
        bad = [m for m in ("jit", "deopt", "gc") if results[m] != oracle]
        if bad:
            failures.append((name, path, oracle, {m: results[m] for m in bad}))

    for name, path, oracle, got in failures:
        print(f"MISMATCH {name}")
        print(f"  interp: {oracle!r}")
        for mode, value in got.items():
            print(f"  {mode:>6}: {value!r}")
        print(f"  program: {path}")

    print(f"kind-mutation fuzz: {ran} cases, {len(failures)} mismatched, "
          f"{skipped} skipped (interpreter rejected)")
    if not failures and not args.keep:
        # rmtree, not unlink: running a program leaves a __jaicache__ DIRECTORY
        # next to it.
        shutil.rmtree(outdir, ignore_errors=True)
    elif failures:
        print(f"generated programs kept in {outdir}")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
