#!/usr/bin/env python3
"""Generate boot/seed.c from the .jaic images the front end needs to start.

The self-hosted front end is written in Jaithon, so compiling it needs a
Jaithon compiler. Today that circle is broken by the C front end, which
compiles the compiler's own closure inside the `sLoadingFrontEnd` window in
src/runtime/module.c. That window is the last thing keeping src/lang, src/sema
and src/codegen alive: everything outside it is already self-hosted.

The seed breaks the circle without a second compiler. It holds the serialised
.jaic image of every module in that closure, as a byte array compiled into the
binary, so a fresh clone builds offline with no extra files and no network.
src/vm/serialize.c already reads .jaic, so loading one costs a memcpy and a
deserialise.

Usage:
    scripts/gen_seed.py <cache-root> <output.c> [subtree ...]

`cache-root` is the tree module names are relative to -- normally `lib`, so
that lib/std/__jaicache__/list.jaic is "std.list". The optional subtrees limit
which caches are collected; without them the whole root is walked.

The limit is not an optimisation. Running the compiler writes cache entries for
whatever it happens to import, so a walk of the whole root embeds a set that
varies from run to run: measured, 44 modules and then 47 across two reseeds of
an unchanged tree. A seed that does not converge is the one failure a bootstrap
cannot recover from on its own, so what gets embedded has to be exactly what
the populate step set out to build, not whatever was found afterwards.
"""

import os
import sys


def module_name_for(jaic_path, root):
    """`<root>/std/__jaicache__/list.jaic` -> `std.list`.

    The cache mirrors the source tree with a __jaicache__ directory beside each
    module, so the module name is the path with that directory removed and the
    separators turned into dots. Deriving it from the path rather than reading
    it out of the image keeps this script independent of the container format.
    """
    rel = os.path.relpath(jaic_path, root)
    parts = rel.split(os.sep)
    if "__jaicache__" not in parts:
        return None
    parts.remove("__jaicache__")
    if not parts or not parts[-1].endswith(".jaic"):
        return None
    parts[-1] = parts[-1][: -len(".jaic")]
    return ".".join(parts)


def collect(root, subtrees):
    found = {}
    for subtree in subtrees:
        for dirpath, _dirnames, filenames in os.walk(subtree):
            if os.path.basename(dirpath) != "__jaicache__":
                continue
            for name in filenames:
                if not name.endswith(".jaic"):
                    continue
                path = os.path.join(dirpath, name)
                module = module_name_for(path, root)
                if module is None:
                    continue
                with open(path, "rb") as f:
                    found[module] = f.read()
    return dict(sorted(found.items()))


def c_bytes(blob, indent="    "):
    out = []
    for i in range(0, len(blob), 16):
        row = ", ".join("0x%02x" % b for b in blob[i : i + 16])
        out.append(indent + row + ",")
    return "\n".join(out)


def main():
    if len(sys.argv) < 3:
        sys.stderr.write(
            "usage: gen_seed.py <cache-root> <output.c> [subtree ...]\n"
        )
        return 2

    root, out_path = sys.argv[1], sys.argv[2]
    subtrees = sys.argv[3:] or [root]
    images = collect(root, subtrees)
    if not images:
        sys.stderr.write(
            "gen_seed.py: no .jaic images under %r.\n"
            "Run the compiler once so __jaicache__ is populated, then reseed.\n"
            "An empty seed would build and then fail at run time, so this is "
            "an error rather than an empty table.\n" % root
        )
        return 1

    total = sum(len(v) for v in images.values())

    with open(out_path, "w") as f:
        f.write(
            "/* Generated by scripts/gen_seed.py. Do not edit.\n"
            " *\n"
            " * The .jaic images the self-hosted front end needs before it can\n"
            " * compile anything, including itself. See scripts/gen_seed.py for\n"
            " * why this exists and `make reseed` for how to regenerate it.\n"
            " *\n"
            " * %d modules, %d bytes.\n"
            " */\n\n"
            '#include "boot/seed.h"\n\n'
            "#include <string.h>\n\n" % (len(images), total)
        )

        for i, (module, blob) in enumerate(images.items()):
            f.write("/* %s */\n" % module)
            f.write("static const unsigned char kImage%d[] = {\n" % i)
            f.write(c_bytes(blob))
            f.write("\n};\n\n")

        f.write("static const JaiSeedEntry kEntries[] = {\n")
        for i, (module, blob) in enumerate(images.items()):
            f.write('    {"%s", kImage%d, sizeof kImage%d},\n' % (module, i, i))
        f.write("};\n\n")

        f.write(
            "const JaiSeedEntry *jaiSeedFind(const char *module) {\n"
            "    if (module == NULL) return NULL;\n"
            "    for (size_t i = 0; i < sizeof kEntries / sizeof kEntries[0];\n"
            "         i++) {\n"
            "        if (strcmp(kEntries[i].module, module) == 0) {\n"
            "            return &kEntries[i];\n"
            "        }\n"
            "    }\n"
            "    return NULL;\n"
            "}\n\n"
            "size_t jaiSeedCount(void) {\n"
            "    return sizeof kEntries / sizeof kEntries[0];\n"
            "}\n"
        )

    sys.stderr.write(
        "gen_seed.py: %d modules, %d bytes -> %s\n" % (len(images), total, out_path)
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
