#!/bin/sh
#: Describe the linked Apple images to the core that will open them.
#:
#:     scripts/dev/gen_native_images.sh <names> <out.h> <out.list> TAG=DYLIB...
#:
#: <names> is the generated list of native functions (see gen_native_bridge.sh).
#: Each TAG=DYLIB is one linked image. Writes <out.h>, compiled into
#: src/native/native_loader.c:
#:
#:   JAI_NATIVE_IMAGE_COUNT   how many images
#:   JAI_NATIVE_IMAGE_FILES   the file name each is installed under beside the
#:                            binary: jaithon-native-TAG-<first 12 hex of its
#:                            LC_UUID>.dylib
#:   JAI_NATIVE_IMAGE_UUIDS   the full LC_UUID, compared against the loaded image
#:   JAI_NATIVE_IMAGE_OF      per name, the image that exports it, or -1 when
#:                            none does and the stub is all there is
#:
#: and <out.list>, one "DYLIB FILE" line per image, for the steps that copy and
#: install them. A name exported by two images is an error: which one a call
#: reached would depend on which a program happened to open first.
#:
#: <out.h> is rewritten only when its text changes, so relinking an image to
#: the same bytes recompiles nothing.

set -eu

names=$1
header=$2
list=$3
shift 3

tmp=$header.tmp.$$
exports=$header.exports.$$
trap 'rm -f "$tmp" "$exports" "$exports".*' EXIT

files=""
uuids=""
: >"$list.tmp"
index=0
for spec in "$@"; do
    tag=${spec%%=*}
    dylib=${spec#*=}
    uuid=$(otool -l "$dylib" | awk '$1 == "uuid" { print $2; exit }' | tr -d - | tr A-F a-f)
    if [ ${#uuid} -ne 32 ]; then
        echo "gen_native_images.sh: no LC_UUID in $dylib" >&2
        exit 1
    fi
    file=jaithon-native-$tag-$(printf '%s' "$uuid" | cut -c1-12).dylib
    bytes=$(printf '%s' "$uuid" | sed 's/\(..\)/0x\1,/g')
    files="$files \"$file\","
    uuids="$uuids {$bytes},"
    printf '%s %s\n' "$dylib" "$file" >>"$list.tmp"
    nm -gUj "$dylib" | sed -n "s/^_\\(jai[A-Za-z0-9_]*\\)\$/\\1 $index/p" >>"$exports"
    index=$((index + 1))
done

# Only the listed names count: every image exports jaiNativeImageInit, by design.
dups=$(awk 'NR == FNR { listed[$1] = 1; next } ($1 in listed) { print $1 }' \
        "$names" "$exports" | sort | uniq -d)
if [ -n "$dups" ]; then
    echo "gen_native_images.sh: exported by more than one image:" $dups >&2
    exit 1
fi

of=$(awk 'NR == FNR { image[$1] = $2; next }
          { printf "%s%s", sep, ($1 in image) ? image[$1] : -1; sep = ", " }' \
        "$exports" "$names")

{
    echo "/* generated by scripts/dev/gen_native_images.sh; do not edit */"
    echo "#define JAI_NATIVE_IMAGE_COUNT $index"
    echo "#define JAI_NATIVE_IMAGE_FILES {$files }"
    echo "#define JAI_NATIVE_IMAGE_UUIDS {$uuids }"
    echo "#define JAI_NATIVE_IMAGE_OF { $of }"
} >"$tmp"

if cmp -s "$tmp" "$header"; then rm -f "$tmp"; else mv -f "$tmp" "$header"; fi
mv -f "$list.tmp" "$list"
