#!/bin/sh
#: Generate the core's side of the split Apple image from a list of names.
#:
#:     scripts/dev/gen_native_bridge.sh <names> <outdir>
#:
#: <names> holds one C function name per line: every native.h function that
#: src/native/stubs.c defines, which is by construction every one the core can
#: call (a Linux build links stubs.c in place of the Apple code, so a function
#: the core calls and stubs.c lacks does not link there). The Makefile derives
#: it by compiling stubs.c alone and reading its symbol table, so there is no
#: hand-kept list to drift. Writes, into <outdir>:
#:
#:   native_list.h    JAI_NATIVE_FN(name) once per name, for X-macro tables
#:   native_rename.h  #define name jaiNativeStub_name, so stubs.c compiled into
#:                    the core defines the fallbacks under names of their own
#:   native_bridge.S  the arm64 trampolines, the slots they jump through, and
#:                    the binder every slot starts at
#:
#: See src/native/native_image.h for the design. Index i in all three files is
#: line i of <names>; native_loader.c relies on that.

set -eu

names=$1
out=$2
mkdir -p "$out"

awk '
BEGIN { print "/* generated by scripts/dev/gen_native_bridge.sh; do not edit */" }
{ printf "JAI_NATIVE_FN(%s)\n", $1 }
' "$names" >"$out/native_list.h.tmp"

awk '
BEGIN {
    print "/* generated by scripts/dev/gen_native_bridge.sh; do not edit */"
    print "#ifndef JAI_GEN_NATIVE_RENAME_H"
    print "#define JAI_GEN_NATIVE_RENAME_H"
}
{ printf "#define %s jaiNativeStub_%s\n", $1, $1 }
END { print "#endif" }
' "$names" >"$out/native_rename.h.tmp"

awk '
BEGIN {
    print "/* generated by scripts/dev/gen_native_bridge.sh; do not edit */"
    print ""
    print "/* One slot per native function. Each starts at its binder and is"
    print " * overwritten, once, by jaiNativeBind in native_loader.c. */"
    print "    .section __DATA,__data"
    print "    .p2align 3"
    print "    .globl _jaiNativeSlots"
    print "_jaiNativeSlots:"
}
{ name[NR - 1] = $1; printf "    .quad Lbind_%d\n", NR - 1 }
END {
    n = NR
    print ""
    print "    .text"
    print ""
    print "/* The trampoline every core caller reaches: load the slot, jump. x16 is"
    print " * the intra-procedure-call scratch register, free at a call boundary. */"
    for (i = 0; i < n; i++) {
        printf "    .p2align 2\n"
        printf "    .globl _%s\n", name[i]
        printf "_%s:\n", name[i]
        printf "    adrp x16, _jaiNativeSlots@PAGE+%d\n", 8 * i
        printf "    ldr  x16, [x16, _jaiNativeSlots@PAGEOFF+%d]\n", 8 * i
        printf "    br   x16\n"
    }
    print ""
    print "/* A slot that has not been bound yet lands here with its index in w17. */"
    for (i = 0; i < n; i++) {
        printf "Lbind_%d:\n", i
        printf "    mov  w17, #%d\n", i
        printf "    b    Lbind_common\n"
    }
    print ""
    print "/* Save every argument register -- x0-x7, the indirect-result x8, q0-q7 --"
    print " * call jaiNativeBind(index), restore them and continue into whatever the"
    print " * slot now holds. Stack-passed arguments sit above this frame untouched."
    print " * x30 still holds the original caller, since the trampoline branched"
    print " * without linking, so the real function returns straight to it. */"
    print "    .p2align 2"
    print "Lbind_common:"
    print "    stp  x29, x30, [sp, #-16]!"
    print "    mov  x29, sp"
    print "    sub  sp, sp, #208"
    print "    stp  x0, x1, [sp, #0]"
    print "    stp  x2, x3, [sp, #16]"
    print "    stp  x4, x5, [sp, #32]"
    print "    stp  x6, x7, [sp, #48]"
    print "    str  x8, [sp, #64]"
    print "    stp  q0, q1, [sp, #80]"
    print "    stp  q2, q3, [sp, #112]"
    print "    stp  q4, q5, [sp, #144]"
    print "    stp  q6, q7, [sp, #176]"
    print "    mov  w0, w17"
    print "    bl   _jaiNativeBind"
    print "    mov  x16, x0"
    print "    ldp  q6, q7, [sp, #176]"
    print "    ldp  q4, q5, [sp, #144]"
    print "    ldp  q2, q3, [sp, #112]"
    print "    ldp  q0, q1, [sp, #80]"
    print "    ldr  x8, [sp, #64]"
    print "    ldp  x6, x7, [sp, #48]"
    print "    ldp  x4, x5, [sp, #32]"
    print "    ldp  x2, x3, [sp, #16]"
    print "    ldp  x0, x1, [sp, #0]"
    print "    mov  sp, x29"
    print "    ldp  x29, x30, [sp], #16"
    print "    br   x16"
}
' "$names" >"$out/native_bridge.S.tmp"

# Rewrite only what changed, so a rebuild that leaves the list alone does not
# recompile stubs.c and the loader.
for f in native_list.h native_rename.h native_bridge.S; do
    if cmp -s "$out/$f.tmp" "$out/$f"; then
        rm -f "$out/$f.tmp"
    else
        mv "$out/$f.tmp" "$out/$f"
    fi
done
