/* serialize.c — the .jaic bytecode container (spec/BYTECODE.md §4-§7).
 *
 * Every integer is little-endian. Writing goes through JaiBuf; reading goes
 * through a bounds-checked Cursor whose every accessor validates the remaining
 * length first, because a .jaic file is untrusted input that may be truncated,
 * corrupt, or hostile. A malformed file always yields NULL: never an
 * out-of-bounds read, never an allocation sized from a corrupt length field,
 * and never a half-updated ObjModule.
 *
 * Where a value cannot be expressed on disk the writer refuses it rather than
 * writing an approximation, so a cache miss (recompile) is the worst outcome.
 * The one such case left is FN_INIT: it is bit 8 of ObjFunction.flags but §5
 * stores flags in one byte, so the bit is recomputed at load time from
 * "FN_METHOD and named init", and the writer verifies that rule holds for the
 * function it is writing rather than dropping the bit silently.
 *
 * A class is not a constant and has no pool tag. §6's spec constant is an
 * ordinary tuple, so it round-trips through K_TUPLE with no help from here;
 * the fields, methods and traits it does not carry arrive as FIELD_DEF,
 * METHOD and IMPL_TRAIT instructions in the class body, which are just code.
 *
 * Inline caches are not stored. They must start empty anyway, so the loader
 * sizes them by scanning the code for cache-bearing opcodes, which doubles as
 * a decodability check on the instruction stream.
 *
 * Chunk.constIndex is not stored either: it is derived from the constant pool,
 * and jaiFunctionNew leaves it NULL so jaiChunkAddConstant rebuilds it from the
 * loaded pool if a later pass appends to it.
 */

/* Feature macros must precede every include: getpid/unlink/rmdir/lstat and
 * <dirent.h> are POSIX, not C11. */
#if !defined(_POSIX_C_SOURCE)
#  define _POSIX_C_SOURCE 200809L
#endif
#if defined(__APPLE__) && !defined(_DARWIN_C_SOURCE)
#  define _DARWIN_C_SOURCE
#endif

#include "vm/bytecode/serialize.h"

#include "vm/bytecode/verify.h"

#include <dirent.h>
#include <limits.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>

#include "vm/bytecode/chunk.h"
#include "vm/gc.h"
#include "vm/object/object.h"

/* Generated by the Makefile from a hash of every source file under src/.
 * JAI_COMPILER_VERSION is hand-maintained and was repeatedly forgotten, so a
 * newer compiler silently replayed bytecode an older one had written. This
 * makes that impossible: any source edit invalidates every cached image. */
#include "jai_build_id.h"
#include "vm/table.h"

/* Constant-pool tags (spec §4). 7 and 9 are missing on purpose: they were a
 * class-spec record and a serialised type descriptor, and neither is written by
 * either front end. They are not free, though -- jaic.jai still DECODES them --
 * so a new tag takes the next unused number rather than reusing one. That is
 * what keeps "a tag this reader does not know" always a newer format and never
 * an older one misread. An unknown tag refuses the image, which recompiles. */
typedef enum {
    K_NULL  = 0,
    K_BOOL  = 1,
    K_INT   = 2,
    K_FLOAT = 3,
    K_STR   = 4,
    K_BYTES = 5,
    K_FUNC  = 6,
    K_TUPLE = 8,
    /* An index into the module's string table (§4). From JAIC_VERSION_STRTAB on
     * this replaces K_STR everywhere: 62.5% of a .jaic's string payload was one
     * text repeated across nested function pools, and 94.9% of strings are
     * under 16 bytes yet each paid a 4-byte u32 length. K_STR stays defined
     * because older containers still use it.
     *
     * 10, NOT 7. The header above says 7 and 9 were never written by either
     * front end; that is true of the writers and false of the readers.
     * lib/jaithon/compile/jaic.jai decodes 7 as a class-spec record and 9 as a
     * type descriptor, so claiming 7 here would have made the two
     * implementations disagree about the same byte, silently, in the one
     * direction nothing in the tree compares. */
    K_STRREF = 10,
} ConstTag;

#define JAIC_CACHE_DIR   "__jaicache__"
#define JAIC_SUFFIX      ".jaic"
#define JAIC_SOURCE_EXT  ".jai"

/* The debug sidecar: the line tables a stripped .jaic left out, beside it under
 * the same stem. Its own magic and checksum, and its srcHash must equal the
 * image's -- a .jaid that does not match is ignored rather than lined up
 * against the wrong records. Missing entirely is not an error: a release
 * install can simply not ship them, and tracebacks fall back to function name
 * plus code offset. */
#define JAID_MAGIC       "JAID"
#define JAID_VERSION     1u
#define JAID_SUFFIX      ".jaid"
#define JAID_HEADER      16u   /* magic 4, version 2, reserved 2, srcHash 8 */

/* A function record has no name when its nameIndex is this sentinel; §5 has no
 * other way to say "unnamed", and index 0 is a perfectly good constant. */
#define JAIC_NO_NAME     UINT32_MAX

/* Nesting bound for FUNC/TUPLE records. Deep nesting is legitimate but a
 * crafted file must not be able to recurse the C stack to death. */
#define JAIC_MAX_DEPTH   64

/* Matches the u24 constant operand: a pool can never exceed this. */
#define JAIC_CONST_MAX   (1u << 24)

/* On-disk sizes of the fixed-width records, used to bound counts against the
 * bytes actually left in the buffer before anything is allocated. */
#define JAIC_LINE_ENTRY   12u   /* u32 offset, u32 span, u32 spanEnd */
#define JAIC_EXC_ENTRY    16u   /* u32 start, end, handler, typeConst */
#define JAIC_U32_ENTRY     4u

/* Flag bits an ObjFunction may carry. Anything else is a newer compiler's
 * output that this reader would silently misinterpret. */
#define JAIC_KNOWN_FN_FLAGS ((uint32_t)0xFFu | (uint32_t)FN_INIT)

/* ------------------------------------------------------------------ */
/* Reading: bounds-checked cursor                                       */
/* ------------------------------------------------------------------ */

typedef struct Cursor_ {
    const uint8_t *data;
    size_t         size;
    size_t         pos;
    bool           bad;   /* sticky: set by the first read that ran short */
    /* The container version this image declares. Carried on the cursor rather
     * than through every signature because only one section reads it -- the
     * line table, whose encoding changed at JAIC_VERSION_LTV1 -- and threading
     * it through readConstant/readTuple/readFunction would touch six
     * signatures to reach one branch. */
    uint16_t       version;
    /* The module string table, from JAIC_VERSION_STRTAB on: every K_STRREF is
     * an index into it. Interned once here rather than once per occurrence --
     * across lib that is 2,327 interns instead of 9,988. Owned by deserialize,
     * which frees the array (not the strings, which the intern table owns). */
    Value         *strings;
    uint32_t       stringCount;
    /* The .jaid's line-table stream, when the image was written stripped. Read
     * in lockstep with the records, because both were produced by the same
     * traversal in the same order. NULL means the spans are inline (a debug
     * image) or simply absent (a release install without its sidecar). */
    struct Cursor_ *sidecar;
} Cursor;

static size_t curLeft(const Cursor *c) {
    if (c->bad || c->pos > c->size) return 0;
    return c->size - c->pos;
}

/* Hands back `n` bytes at the cursor and advances, or marks the cursor bad.
 * Every other read is built on this one, so no read can escape the buffer. */
static bool curTake(Cursor *c, size_t n, const uint8_t **out) {
    if (c->bad || n > curLeft(c)) {
        c->bad = true;
        return false;
    }
    if (out != NULL) *out = c->data + c->pos;
    c->pos += n;
    return true;
}

static bool curSkip(Cursor *c, size_t n) { return curTake(c, n, NULL); }

/* True when `count` records of `each` bytes can still fit. Counts come from
 * the file, so this is what stops a corrupt length from sizing an allocation. */
static bool curFits(const Cursor *c, uint64_t count, uint64_t each) {
    return !c->bad && count <= (uint64_t)curLeft(c) / (each > 0 ? each : 1);
}

static uint8_t curU8(Cursor *c) {
    const uint8_t *p;
    if (!curTake(c, 1, &p)) return 0;
    return p[0];
}

static uint16_t curU16(Cursor *c) {
    const uint8_t *p;
    if (!curTake(c, 2, &p)) return 0;
    return (uint16_t)((uint16_t)p[0] | ((uint16_t)p[1] << 8));
}

static uint32_t curU32(Cursor *c) {
    const uint8_t *p;
    if (!curTake(c, 4, &p)) return 0;
    return (uint32_t)p[0] | ((uint32_t)p[1] << 8) | ((uint32_t)p[2] << 16) |
           ((uint32_t)p[3] << 24);
}

static uint64_t curU64(Cursor *c) {
    const uint8_t *p;
    if (!curTake(c, 8, &p)) return 0;
    uint64_t v = 0;
    for (int i = 0; i < 8; i++) v |= (uint64_t)p[i] << (8 * i);
    return v;
}

static double curF64(Cursor *c) {
    uint64_t bits = curU64(c);
    double d;
    memcpy(&d, &bits, sizeof d);   /* IEEE-754 bit pattern, as written */
    return d;
}

/* LEB128, bounded by the cursor. A malformed run refuses the image rather than
 * spinning: 10 bytes is the most a 64-bit value can occupy. */
static bool curUleb(Cursor *c, uint64_t *out) {
    uint64_t v = 0;
    int shift = 0;
    for (int i = 0; i < 10; i++) {
        const uint8_t *p = NULL;
        if (!curTake(c, 1, &p)) return false;
        if (shift < 64) v |= (uint64_t)(p[0] & 0x7Fu) << shift;
        shift += 7;
        if ((p[0] & 0x80u) == 0) {
            *out = v;
            return true;
        }
    }
    c->bad = true;
    return false;
}

/* The module string table: count, then {uleb128 length, bytes} each. Interning
 * happens exactly once per distinct text, here.
 *
 * The array is a GC ROOT RANGE for the whole of the rest of the load. The
 * intern table's references are weak (spec §10), so an interned string reachable
 * only from this C array would be swept by the first collection the remaining
 * reads trigger -- and they allocate a function object per record. Pushing the
 * range up front, pre-filled with NULL_VAL so a collection mid-fill marks a
 * well-formed range, is what keeps them alive until the pools point at them.
 * The caller pops it. */
static bool readStrTab(Cursor *c) {
    uint64_t count = 0;
    if (!curUleb(c, &count)) return false;
    if (count >= JAIC_CONST_MAX) return false;
    if (count == 0) return true;
    /* One byte minimum per entry (a zero-length string is one length byte), so
     * a corrupt count cannot size an allocation larger than the file. */
    if (!curFits(c, count, 1)) return false;

    c->strings = JAI_ALLOC(Value, (size_t)count);
    for (uint64_t i = 0; i < count; i++) c->strings[i] = NULL_VAL;
    c->stringCount = (uint32_t)count;
    jaiGCPushRootRange(c->strings, (int)count);

    for (uint64_t i = 0; i < count; i++) {
        uint64_t len = 0;
        if (!curUleb(c, &len)) return false;
        if (len > curLeft(c)) return false;
        const uint8_t *p = NULL;
        if (!curTake(c, (size_t)len, &p)) return false;
        ObjString *s = jaiStringIntern((const char *)p, (uint32_t)len);
        if (s == NULL) return false;
        c->strings[i] = OBJ_VAL(s);
    }
    return true;
}

static uint32_t readU32At(const uint8_t *p) {
    return (uint32_t)p[0] | ((uint32_t)p[1] << 8) | ((uint32_t)p[2] << 16) |
           ((uint32_t)p[3] << 24);
}

/* ------------------------------------------------------------------ */
/* Writing: the constant pool of one function record                    */
/* ------------------------------------------------------------------ */

/* A record's pool is the chunk's pool plus whatever the record needs to name
 * by index and the chunk did not already hold: the function's own name, its
 * parameter names, and the names a class spec refers to. Appended entries land
 * after the chunk's own constants, so every existing u24 operand in the code
 * keeps pointing at the same value. */
typedef struct {
    const ValueArray *pool;
    ValueArray        extra;
} PoolWriter;

static uint32_t poolTotal(const PoolWriter *w) {
    return (uint32_t)w->pool->count + (uint32_t)w->extra.count;
}

static Value poolAt(const PoolWriter *w, uint32_t i) {
    if (i < (uint32_t)w->pool->count) return w->pool->data[i];
    return w->extra.data[i - (uint32_t)w->pool->count];
}

/* Exact identity for the values a record names by index: strings compare by
 * content (two equal literals must share one entry), everything else by
 * pointer. Never jaiValuesEqual, which runs user code and conflates int with
 * float. */
static bool poolSame(Value a, Value b) {
    if (!IS_OBJ(a) || !IS_OBJ(b)) return false;
    Obj *x = AS_OBJ(a), *y = AS_OBJ(b);
    if (x == y) return true;
    if (x == NULL || y == NULL || x->type != y->type) return false;
    if (x->type != OBJ_STRING) return false;

    const ObjString *sa = (const ObjString *)x, *sb = (const ObjString *)y;
    return sa->length == sb->length && sa->hash == sb->hash &&
           memcmp(sa->chars, sb->chars, sa->length) == 0;
}

static bool poolIndexOf(PoolWriter *w, Value v, uint32_t *out) {
    uint32_t total = poolTotal(w);
    for (uint32_t i = 0; i < total; i++) {
        if (poolSame(poolAt(w, i), v)) {
            *out = i;
            return true;
        }
    }
    if (total >= JAIC_CONST_MAX) return false;

    jaiValueArrayPush(&w->extra, v);
    *out = total;
    return true;
}

static bool poolIndexOfString(PoolWriter *w, ObjString *s, uint32_t *out) {
    if (s == NULL) return false;
    return poolIndexOf(w, OBJ_VAL(s), out);
}

/* ------------------------------------------------------------------ */
/* Writing: constants and function records                              */
/* ------------------------------------------------------------------ */

/* ------------------------------------------------------------------ */
/* Writing: the module string table                                     */
/* ------------------------------------------------------------------ */

/* Every string constant in the module, once, in first-use order.
 *
 * Strings are interned, so identity is equality and the dedup index can be a
 * pointer-keyed table. Two things pay for this: 62.5% of a .jaic's string
 * payload was the same text repeated across nested function pools (73.8% in the
 * seed), and interning at load drops from one call per occurrence -- 9,988
 * across lib -- to one per distinct text, 2,327. */
typedef struct {
    const ObjString **items;
    uint32_t          count;
    uint32_t          capacity;
    JaiTable          index;   /* interned string -> INT_VAL(position) */
} StrTab;

static void strTabInit(StrTab *st) {
    st->items = NULL;
    st->count = 0;
    st->capacity = 0;
    jaiTableInit(&st->index);
}

static void strTabFree(StrTab *st) {
    JAI_FREE_ARRAY(const ObjString *, st->items, st->capacity);
    jaiTableFree(&st->index);
    st->items = NULL;
    st->count = 0;
    st->capacity = 0;
}

static bool strTabIntern(StrTab *st, const ObjString *s, uint32_t *out) {
    if (s == NULL) return false;

    Value existing;
    if (jaiTableGetInterned(&st->index, (ObjString *)s, &existing) &&
        IS_INT(existing)) {
        *out = (uint32_t)AS_INT(existing);
        return true;
    }
    if (st->count >= JAIC_CONST_MAX) return false;

    if (st->capacity < st->count + 1) {
        uint32_t oldCapacity = st->capacity;
        st->capacity = (uint32_t)JAI_GROW_CAP((int)oldCapacity);
        st->items = JAI_GROW_ARRAY(const ObjString *, st->items, oldCapacity,
                                   st->capacity);
    }
    st->items[st->count] = s;
    *out = st->count;
    (void)jaiTableSetInterned(&st->index, (ObjString *)s, INT_VAL(st->count));
    st->count++;
    return true;
}

static void bufWriteUleb(JaiBuf *b, uint64_t v) {
    do {
        uint8_t byte = (uint8_t)(v & 0x7Fu);
        v >>= 7;
        if (v != 0) byte |= 0x80u;
        jaiBufPush(b, byte);
    } while (v != 0);
}

/* `count`, then each string as {uleb128 length, bytes}. Varint lengths because
 * 94.9% of strings are under 16 bytes: a flat u32 length cost 38,672 bytes
 * across lib to carry 75,717 bytes of payload. */
static void writeStrTab(JaiBuf *b, const StrTab *st) {
    bufWriteUleb(b, st->count);
    for (uint32_t i = 0; i < st->count; i++) {
        const ObjString *s = st->items[i];
        bufWriteUleb(b, s->length);
        jaiBufAppend(b, s->chars, s->length);
    }
}

/* When `sidecar` is non-NULL the line table is STRIPPED from the image and
 * written there instead: the .jaic gets a zero byte-length and the stream goes
 * to the .jaid beside it. The two stay in step because both are produced by
 * this same traversal, in this same order, one record per function -- including
 * functions with no line entries at all, which write a zero length rather than
 * nothing. */
static bool writeFunction(JaiBuf *b, JaiBuf *sidecar, StrTab *st,
                          const ObjFunction *fn, int depth);
static bool writeConstant(JaiBuf *b, JaiBuf *sidecar, PoolWriter *w, StrTab *st,
                          Value v, int depth);

/* §4. Refusing a value the format cannot express is always allowed: the
 * caller's fallback is to skip the cache and recompile. */
static bool writeConstant(JaiBuf *b, JaiBuf *sidecar, PoolWriter *w, StrTab *st,
                          Value v, int depth) {
    if (depth > JAIC_MAX_DEPTH) return false;

    switch (jaiValueType(v)) {
    case VAL_NULL:
        jaiBufPush(b, K_NULL);
        return true;
    case VAL_BOOL:
        jaiBufPush(b, K_BOOL);
        jaiBufPush(b, AS_BOOL(v) ? 1u : 0u);
        return true;
    case VAL_INT:
        jaiBufPush(b, K_INT);
        jaiBufWriteU64(b, (uint64_t)AS_INT(v));
        return true;
    case VAL_FLOAT:
        jaiBufPush(b, K_FLOAT);
        jaiBufWriteF64(b, AS_FLOAT(v));
        return true;
    case VAL_OBJ:
        break;
    }

    Obj *o = AS_OBJ(v);
    if (o == NULL) return false;

    switch (o->type) {
    case OBJ_STRING: {
        /* The bytes live once, in the module string table; the pool entry is
         * an index into it. */
        uint32_t index = 0;
        if (!strTabIntern(st, (const ObjString *)o, &index)) return false;
        jaiBufPush(b, K_STRREF);
        bufWriteUleb(b, index);
        return true;
    }
    case OBJ_BYTES: {
        const ObjBytes *bytes = (const ObjBytes *)o;
        jaiBufPush(b, K_BYTES);
        jaiBufWriteU32(b, bytes->length);
        jaiBufAppend(b, bytes->data, bytes->length);
        return true;
    }
    case OBJ_FUNCTION:
        jaiBufPush(b, K_FUNC);
        return writeFunction(b, sidecar, st, (const ObjFunction *)o, depth + 1);
    case OBJ_TUPLE: {
        const ObjTuple *t = (const ObjTuple *)o;
        jaiBufPush(b, K_TUPLE);
        jaiBufWriteU32(b, t->count);
        for (uint32_t i = 0; i < t->count; i++) {
            if (!writeConstant(b, sidecar, w, st, t->items[i], depth + 1)) {
                return false;
            }
        }
        return true;
    }
    default:
        /* Lists, dicts, closures, instances: not constants. Refusing beats
         * writing something the loader would have to guess at. */
        return false;
    }
}

/* FN_INIT is bit 8 and §5's flags field is one byte, so the bit is not stored;
 * it is recomputed on load from "a method named init", which is the same rule
 * jaiClassAddMethod already uses to pick a class's initialiser — a method
 * named init is one whether or not the bit is set. Only the case the name
 * cannot recover, a function marked FN_INIT under some other name, loses
 * information, and such a function is not written. */
static bool initFlagIsRecoverable(const ObjFunction *fn) {
    bool marked  = (fn->flags & FN_INIT) != 0;
    bool derived = (fn->flags & FN_METHOD) != 0 && fn->name != NULL &&
                   fn->name->length == 4 &&
                   memcmp(fn->name->chars, "init", 4) == 0;
    return derived || !marked;
}

/* §5. */
static bool writeFunction(JaiBuf *b, JaiBuf *sidecar, StrTab *st,
                          const ObjFunction *fn, int depth) {
    if (fn == NULL || depth > JAIC_MAX_DEPTH) return false;
    if (fn->flags & ~JAIC_KNOWN_FN_FLAGS) return false;
    if (!initFlagIsRecoverable(fn)) return false;
    if (fn->chunk.count < 0 || fn->chunk.lineStreamLen < 0) return false;
    /* A count without its array is a broken object, not a cacheable one. */
    if ((fn->chunk.count > 0 && fn->chunk.code == NULL) ||
        (fn->chunk.lineStreamLen > 0 && fn->chunk.lineStream == NULL) ||
        (fn->exceptionCount > 0 && fn->exceptions == NULL) ||
        (fn->defaultCount > 0 && fn->defaultOffsets == NULL) ||
        (fn->paramCount > 0 && fn->paramNames == NULL)) {
        return false;
    }

    PoolWriter w = { &fn->chunk.constants, { NULL, 0, 0 } };
    JaiBuf constants;
    uint32_t *paramIndices = NULL;
    uint32_t nameIndex = JAIC_NO_NAME;
    bool ok = true;

    jaiBufInit(&constants);

    /* Every index this record names must be resolved before the pool is
     * serialised, since resolving may append to it. Class specs append while
     * the pool is being written, which the loop below picks up. */
    if (fn->name != NULL && !poolIndexOfString(&w, fn->name, &nameIndex)) {
        ok = false;
    }
    if (ok && fn->paramCount > 0) {
        paramIndices = JAI_ALLOC(uint32_t, fn->paramCount);
        for (uint16_t i = 0; i < fn->paramCount && ok; i++) {
            ObjString *name = fn->paramNames[i];
            if (name == NULL) {
                paramIndices[i] = JAIC_NO_NAME;
            } else if (!poolIndexOfString(&w, name, &paramIndices[i])) {
                ok = false;
            }
        }
    }

    for (uint32_t i = 0; ok && i < poolTotal(&w); i++) {
        ok = writeConstant(&constants, sidecar, &w, st, poolAt(&w, i),
                           depth + 1);
    }

    uint32_t constCount = poolTotal(&w);
    if (ok && constCount >= JAIC_CONST_MAX) ok = false;

    if (ok) {
        jaiBufWriteU32(b, nameIndex);
        jaiBufPush(b, fn->arity);
        jaiBufPush(b, (uint8_t)(fn->flags & 0xFFu));
        jaiBufWriteU16(b, fn->maxSlots);
        jaiBufWriteU16(b, fn->upvalueCount);

        jaiBufWriteU32(b, (uint32_t)fn->chunk.count);
        jaiBufAppend(b, fn->chunk.code, (size_t)fn->chunk.count);

        jaiBufWriteU32(b, constCount);
        jaiBufAppend(b, constants.data, constants.count);

        /* The length stays a BYTE count, which is what lets a reader that does
         * not understand the section skip it -- that property is why changing
         * what is inside it is a contained change. The bytes are now the LTV1
         * stream the chunk already holds, so writing the table is a memcpy. */
        if (sidecar != NULL) {
            /* Stripped: the image says "no spans", and the stream goes to the
             * sidecar. A release binary that ships without its .jaid loses
             * source spans in tracebacks and nothing else. */
            jaiBufWriteU32(b, 0);
            jaiBufWriteU32(sidecar, (uint32_t)fn->chunk.lineStreamLen);
            jaiBufAppend(sidecar, fn->chunk.lineStream,
                         (size_t)fn->chunk.lineStreamLen);
        } else {
            jaiBufWriteU32(b, (uint32_t)fn->chunk.lineStreamLen);
            jaiBufAppend(b, fn->chunk.lineStream,
                         (size_t)fn->chunk.lineStreamLen);
        }

        jaiBufWriteU16(b, fn->exceptionCount);
        for (uint16_t i = 0; i < fn->exceptionCount; i++) {
            const ExceptionEntry *e = &fn->exceptions[i];
            jaiBufWriteU32(b, e->start);
            jaiBufWriteU32(b, e->end);
            jaiBufWriteU32(b, e->handler);
            jaiBufWriteU32(b, e->typeConst);
        }

        jaiBufWriteU16(b, fn->defaultCount);
        for (uint8_t i = 0; i < fn->defaultCount; i++) {
            jaiBufWriteU32(b, fn->defaultOffsets[i]);
        }

        jaiBufWriteU16(b, fn->paramCount);
        for (uint16_t i = 0; i < fn->paramCount; i++) {
            jaiBufWriteU32(b, paramIndices[i]);
        }
    }

    if (paramIndices != NULL) JAI_FREE_ARRAY(uint32_t, paramIndices, fn->paramCount);
    jaiBufFree(&constants);
    jaiValueArrayFree(&w.extra);
    return ok;
}

/* ------------------------------------------------------------------ */
/* Writing: the container                                               */
/* ------------------------------------------------------------------ */

/* Last-modified time of the module's source, or 0 when it cannot be read.
 * mtime is informational: cache validity is decided by srcHash and crc32. */
static int64_t sourceMtime(const ObjModule *module) {
    struct stat st;
    if (module == NULL || module->path == NULL) return 0;
    if (stat(module->path->chars, &st) != 0) return 0;
    return (int64_t)st.st_mtime;
}

/* The module-level pool (§7) holds the export and import names; the module
 * body's own constants live in its function record. */
static bool writeModulePool(JaiBuf *b, StrTab *st, ObjModule *module,
                            uint32_t *outCount) {
    uint32_t count = 0;
    if (module != NULL) {
        int slot = 0;
        Value key, value;
        while (jaiTableNext(&module->exports, &slot, &key, &value)) {
            if (IS_STRING(key)) count++;
        }
    }
    if (count >= JAIC_CONST_MAX) return false;

    jaiBufWriteU32(b, count);
    if (module != NULL) {
        int slot = 0;
        Value key, value;
        while (jaiTableNext(&module->exports, &slot, &key, &value)) {
            if (!IS_STRING(key)) continue;
            uint32_t index = 0;
            if (!strTabIntern(st, AS_STRING(key), &index)) return false;
            jaiBufPush(b, K_STRREF);
            bufWriteUleb(b, index);
        }
    }
    *outCount = count;
    return true;
}

uint8_t *jaiSerializeModule(ObjModule *module, ObjFunction *body,
                            uint64_t sourceHash, uint32_t flags,
                            size_t *outSize, uint8_t **outSidecar,
                            size_t *outSidecarSize) {
    if (outSize != NULL) *outSize = 0;
    if (outSidecar != NULL) *outSidecar = NULL;
    if (outSidecarSize != NULL) *outSidecarSize = 0;
    if (body == NULL || flags > 0xFFFFu) return NULL;

    /* The line table is 37% of what a .jaic still weighs after LTV1, and a
     * release build has no use for it until something throws. Absent
     * JAIC_FLAG_DEBUG it goes to a .jaid beside the image, which a release
     * install can simply not ship. */
    bool strip = (flags & JAIC_FLAG_DEBUG) == 0 && outSidecar != NULL;
    JaiBuf sidecarBuf;
    jaiBufInit(&sidecarBuf);
    JaiBuf *sidecar = strip ? &sidecarBuf : NULL;

    JaiBuf b;
    jaiBufInit(&b);
    jaiBufAppend(&b, JAIC_MAGIC, 4);
    jaiBufWriteU16(&b, JAIC_VERSION);
    jaiBufWriteU16(&b, (uint16_t)flags);
    jaiBufWriteU32(&b, JAI_COMPILER_VERSION);
    jaiBufWriteU32(&b, JAI_BUILD_ID);
    jaiBufWriteU64(&b, sourceHash);

    const ObjString *path = module != NULL ? module->path : NULL;
    uint32_t pathLen = path != NULL ? path->length : 0;
    if (pathLen > UINT16_MAX) {
        jaiBufFree(&b);
        return NULL;
    }
    jaiBufWriteU16(&b, (uint16_t)pathLen);
    if (pathLen > 0) jaiBufAppend(&b, path->chars, pathLen);
    jaiBufWriteU64(&b, (uint64_t)sourceMtime(module));

    /* The body is built into its own buffer first, because the string table has
     * to be complete before it can be written and it is only complete once
     * every nested function record has been walked. The table then goes ahead
     * of the body, so the reader has it before the first K_STRREF. */
    StrTab st;
    strTabInit(&st);
    JaiBuf body_buf;
    jaiBufInit(&body_buf);

    uint32_t exportCount = 0;
    bool ok = writeModulePool(&body_buf, &st, module, &exportCount);
    if (ok) ok = writeFunction(&body_buf, sidecar, &st, body, 0);

    if (ok) {
        jaiBufWriteU32(&body_buf, exportCount);
        for (uint32_t i = 0; i < exportCount; i++) {
            /* the pool holds exactly the export names */
            jaiBufWriteU32(&body_buf, i);
        }
        /* ObjModule keeps no import list; the body's OP_IMPORT instructions
         * are what actually import. The section stays for format conformance. */
        jaiBufWriteU32(&body_buf, 0);
    }

    if (ok) {
        writeStrTab(&b, &st);
        jaiBufAppend(&b, body_buf.data, body_buf.count);
    }

    jaiBufFree(&body_buf);
    strTabFree(&st);

    if (!ok) {
        jaiBufFree(&b);
        jaiBufFree(&sidecarBuf);
        return NULL;
    }

    if (strip && sidecarBuf.count > 0) {
        /* Its own magic and checksum: a .jaid that does not match its .jaic is
         * ignored, never trusted to line up with the wrong image. srcHash is
         * what ties them together. */
        JaiBuf sc;
        jaiBufInit(&sc);
        jaiBufAppend(&sc, JAID_MAGIC, 4);
        jaiBufWriteU16(&sc, JAID_VERSION);
        jaiBufWriteU16(&sc, 0);
        jaiBufWriteU64(&sc, sourceHash);
        jaiBufAppend(&sc, sidecarBuf.data, sidecarBuf.count);
        jaiBufWriteU32(&sc, jaiCrc32(sc.data, sc.count));
        if (outSidecar != NULL) *outSidecar = sc.data;
        if (outSidecarSize != NULL) *outSidecarSize = sc.count;
    }
    jaiBufFree(&sidecarBuf);

    jaiBufWriteU32(&b, jaiCrc32(b.data, b.count));

    size_t size = b.count;
    uint8_t *data = b.data;
    if (b.capacity > size) data = (uint8_t *)jaiRealloc(b.data, b.capacity, size);
    jaiBufInit(&b);

    if (outSize != NULL) *outSize = size;
    return data;
}

/* ------------------------------------------------------------------ */
/* Reading: constants                                                   */
/* ------------------------------------------------------------------ */

static ObjFunction *readFunction(Cursor *c, ObjModule *module, int depth);

static ObjString *poolString(const ValueArray *pool, uint32_t index) {
    if (index >= (uint32_t)pool->count) return NULL;
    Value v = pool->data[index];
    return IS_STRING(v) ? AS_STRING(v) : NULL;
}

/* Reads a length-prefixed byte run, capping the length against what is left in
 * the buffer before anything is allocated. */
static bool readBlob(Cursor *c, const uint8_t **out, uint32_t *outLen) {
    uint32_t len = curU32(c);
    if (c->bad || len > curLeft(c)) {
        c->bad = true;
        return false;
    }
    const uint8_t *p = NULL;
    if (len > 0 && !curTake(c, len, &p)) return false;
    *out = p;
    *outLen = len;
    return true;
}

static bool readConstant(Cursor *c, ObjModule *module, Value *out, int depth);

static bool readTuple(Cursor *c, ObjModule *module, Value *out, int depth) {
    uint32_t count = curU32(c);
    if (c->bad || count > JAIC_CONST_MAX || !curFits(c, count, 1) ||
        count > (uint32_t)INT_MAX) {
        return false;
    }

    Value *items = count > 0 ? JAI_ALLOC(Value, count) : NULL;
    int rooted = 0;
    bool ok = true;

    for (uint32_t i = 0; i < count && ok; i++) {
        Value v;
        ok = readConstant(c, module, &v, depth + 1);
        if (!ok) break;
        items[i] = v;
        /* Held only in `items`, which the collector cannot see. */
        jaiGCPushRoot(v);
        rooted++;
    }

    ObjTuple *t = ok ? jaiTupleNew(items, (int)count) : NULL;
    jaiGCPopRoots(rooted);
    if (items != NULL) JAI_FREE_ARRAY(Value, items, count);

    if (!ok || t == NULL) return false;
    *out = OBJ_VAL(t);
    return true;
}

static bool readConstant(Cursor *c, ObjModule *module, Value *out, int depth) {
    if (depth > JAIC_MAX_DEPTH) {
        c->bad = true;
        return false;
    }

    uint8_t tag = curU8(c);
    if (c->bad) return false;

    switch (tag) {
    case K_NULL:
        *out = NULL_VAL;
        return true;
    case K_BOOL: {
        uint8_t v = curU8(c);
        if (c->bad || v > 1) return false;
        *out = BOOL_VAL(v != 0);
        return true;
    }
    case K_INT: {
        uint64_t bits = curU64(c);
        if (c->bad) return false;
        *out = INT_VAL((int64_t)bits);
        return true;
    }
    case K_FLOAT: {
        double d = curF64(c);
        if (c->bad) return false;
        *out = FLOAT_VAL(d);
        return true;
    }
    case K_STRREF: {
        uint64_t index = 0;
        if (!curUleb(c, &index)) return false;
        if (c->strings == NULL || index >= c->stringCount) return false;
        if (!IS_STRING(c->strings[index])) return false;   /* corrupt table */
        *out = c->strings[index];
        return true;
    }
    case K_BYTES: {
        const uint8_t *p = NULL;
        uint32_t len = 0;
        if (!readBlob(c, &p, &len)) return false;
        ObjBytes *bytes = jaiBytesNew(p, len);
        if (bytes == NULL) return false;
        *out = OBJ_VAL(bytes);
        return true;
    }
    case K_FUNC: {
        ObjFunction *fn = readFunction(c, module, depth + 1);
        if (fn == NULL) return false;
        *out = OBJ_VAL(fn);
        return true;
    }
    case K_TUPLE:
        return readTuple(c, module, out, depth);
    default:
        return false;
    }
}

/* Reads `count` constants into `out`. Every tag §4 defines is self-contained,
 * so one forward pass is enough: no constant refers to a later one.
 *
 * When `pushedRoots` is non-NULL the caller has no other reference to `out`,
 * so every stored value is also pushed as a GC temp root and the count is
 * reported back for the caller to pop, on the failure path too. */
static bool readConstantPool(Cursor *c, ObjModule *module, ValueArray *out,
                             uint32_t count, int depth, int *pushedRoots) {
    for (uint32_t i = 0; i < count; i++) {
        if (curLeft(c) == 0) return false;

        Value v = NULL_VAL;
        if (!readConstant(c, module, &v, depth)) return false;

        jaiValueArrayPush(out, v);
        if (pushedRoots != NULL) {
            jaiGCPushRoot(v);
            (*pushedRoots)++;
        }
    }
    return true;
}

/* ------------------------------------------------------------------ */
/* Reading: function records                                            */
/* ------------------------------------------------------------------ */

/* Inline-cache slots are not serialised — they must start empty — so their
 * number is recovered by decoding the code and taking the highest cache
 * operand. Walking the stream also proves it decodes cleanly; a file whose
 * instructions do not tile the code array exactly is rejected. */
static bool rebuildCaches(Chunk *chunk) {
    long maxIndex = -1;

    for (int off = 0; off < chunk->count;) {
        uint8_t raw = chunk->code[off];
        if (raw >= OP_COUNT) return false;
        OpCode op = (OpCode)raw;

        int size = jaiOpOperandSize(op);
        if (op == OP_CLOSURE) {
            if (off + 1 + 3 > chunk->count) return false;
            uint32_t k = jaiReadU24(chunk->code + off + 1);
            if (k >= (uint32_t)chunk->constants.count) return false;
            Value fn = chunk->constants.data[k];
            if (!IS_FUNCTION(fn)) return false;
            size = 3 + 3 * (int)AS_FUNCTION(fn)->upvalueCount;
        }
        if (size < 0 || off > chunk->count - 1 - size) return false;

        int cacheAt = jaiOpCacheOperand(op);
        if (cacheAt >= 0) {
            long idx = (long)jaiReadU16(chunk->code + off + 1 + cacheAt);
            if (idx > maxIndex) maxIndex = idx;
        }
        off += 1 + size;
    }

    /* Exactly maxIndex + 1 slots, not JAI_GROW_CAP's next power of two: the
     * count is known here, and the rounding cost 1.19 MB across the seed's
     * images. maxIndex starts at -1, so a chunk with no cache operands reserves
     * zero and allocates nothing. */
    return jaiChunkReserveCaches(chunk, (int)(maxIndex + 1)) &&
           chunk->cacheCount == (int)(maxIndex + 1);
}

/* §5. Returns an unrooted function; callers store it immediately, and no
 * allocation happens in between. */
static ObjFunction *readFunction(Cursor *c, ObjModule *module, int depth) {
    if (depth > JAIC_MAX_DEPTH) {
        c->bad = true;
        return NULL;
    }

    ObjFunction *fn = jaiFunctionNew();
    jaiGCPushRoot(OBJ_VAL(fn));
    int roots = 1;

    fn->module = module;
    fn->chunk.sourceFileId = module != NULL ? module->sourceFileId : -1;

    uint32_t nameIndex = curU32(c);
    uint8_t arity = curU8(c);
    uint8_t flags = curU8(c);
    uint16_t maxSlots = curU16(c);
    uint16_t upvalueCount = curU16(c);
    if (c->bad || upvalueCount > JAI_MAX_UPVALUES) goto fail;

    {
        uint32_t codeLength = curU32(c);
        if (c->bad || codeLength > curLeft(c) || codeLength > (uint32_t)INT_MAX) {
            goto fail;
        }
        if (codeLength > 0) {
            const uint8_t *p = NULL;
            if (!curTake(c, codeLength, &p)) goto fail;
            fn->chunk.code = JAI_ALLOC(uint8_t, codeLength);
            memcpy(fn->chunk.code, p, codeLength);
            fn->chunk.count = (int)codeLength;
            fn->chunk.capacity = (int)codeLength;
        }
    }

    {
        uint32_t constCount = curU32(c);
        if (c->bad || constCount >= JAIC_CONST_MAX || !curFits(c, constCount, 1)) {
            goto fail;
        }
        /* The pool hangs off the rooted function, so its entries need no
         * roots of their own. */
        if (!readConstantPool(c, module, &fn->chunk.constants, constCount,
                              depth + 1, NULL)) {
            goto fail;
        }
    }

    {
        uint32_t lineBytes = curU32(c);
        if (c->bad || lineBytes > curLeft(c) || lineBytes > (uint32_t)INT_MAX) {
            goto fail;
        }
        /* A stripped image says zero here and the bytes live in the .jaid. The
         * sidecar is advanced for EVERY record, including ones with no entries,
         * so the two stay aligned. */
        Cursor *lineSrc = c;
        if (lineBytes == 0 && c->sidecar != NULL) {
            uint32_t sidecarBytes = curU32(c->sidecar);
            if (c->sidecar->bad || sidecarBytes > curLeft(c->sidecar)) {
                /* A malformed sidecar costs spans, not the load. */
                c->sidecar = NULL;
            } else {
                lineBytes = sidecarBytes;
                lineSrc = c->sidecar;
            }
        }
        if (lineBytes > 0) {
            /* The on-disk bytes ARE the runtime form, so loading the table
             * is one copy and no decode at all. */
            const uint8_t *p = NULL;
            if (!curTake(lineSrc, lineBytes, &p)) goto fail;
            fn->chunk.lineStream = JAI_ALLOC(uint8_t, lineBytes);
            memcpy(fn->chunk.lineStream, p, lineBytes);
            fn->chunk.lineStreamLen = (int)lineBytes;
            fn->chunk.lineStreamCap = (int)lineBytes;
        }
    }

    {
        uint16_t excCount = curU16(c);
        if (c->bad || !curFits(c, excCount, JAIC_EXC_ENTRY)) goto fail;
        if (excCount > 0) {
            fn->exceptions = JAI_ALLOC(ExceptionEntry, excCount);
            fn->exceptionCount = excCount;
            for (uint16_t i = 0; i < excCount; i++) {
                fn->exceptions[i].start = curU32(c);
                fn->exceptions[i].end = curU32(c);
                fn->exceptions[i].handler = curU32(c);
                fn->exceptions[i].typeConst = curU32(c);
            }
            if (c->bad) goto fail;
        }
    }

    {
        uint16_t defaultCount = curU16(c);
        if (c->bad || defaultCount > UINT8_MAX ||
            !curFits(c, defaultCount, JAIC_U32_ENTRY)) {
            goto fail;
        }
        if (defaultCount > 0) {
            fn->defaultOffsets = JAI_ALLOC(uint32_t, defaultCount);
            fn->defaultCount = (uint8_t)defaultCount;
            for (uint16_t i = 0; i < defaultCount; i++) {
                fn->defaultOffsets[i] = curU32(c);
            }
            if (c->bad) goto fail;
        }
    }

    {
        uint16_t paramCount = curU16(c);
        if (c->bad || !curFits(c, paramCount, JAIC_U32_ENTRY)) goto fail;
        if (paramCount > 0) {
            ObjString **names = JAI_ALLOC(ObjString *, paramCount);
            memset(names, 0, sizeof(ObjString *) * (size_t)paramCount);
            fn->paramNames = names;
            fn->paramCount = paramCount;
            for (uint16_t i = 0; i < paramCount; i++) {
                uint32_t idx = curU32(c);
                if (idx == JAIC_NO_NAME) continue;
                names[i] = poolString(&fn->chunk.constants, idx);
                if (names[i] == NULL) goto fail;
            }
            if (c->bad) goto fail;
        }
    }

    if (nameIndex != JAIC_NO_NAME) {
        ObjString *name = poolString(&fn->chunk.constants, nameIndex);
        if (name == NULL) goto fail;
        fn->name = name;
        fn->qualifiedName = name;   /* §5 stores no qualified name */
    }

    fn->arity = arity;
    fn->flags = flags;
    fn->maxSlots = maxSlots;
    fn->upvalueCount = upvalueCount;
    if ((flags & FN_METHOD) && fn->name != NULL && fn->name->length == 4 &&
        memcmp(fn->name->chars, "init", 4) == 0) {
        fn->flags |= FN_INIT;   /* see initFlagIsRecoverable */
    }

    /* Offsets the VM will branch to must land inside this chunk. The checksum
     * says the bytes are unaltered, but it says nothing about the compiler
     * that produced them; a handler pointing past the code would become a wild
     * jump. Full well-formedness is jaiVerifyChunk's job. */
    for (uint16_t i = 0; i < fn->exceptionCount; i++) {
        const ExceptionEntry *e = &fn->exceptions[i];
        if (e->start > e->end || e->end > (uint32_t)fn->chunk.count ||
            e->handler >= (uint32_t)fn->chunk.count) {
            goto fail;
        }
        if (e->typeConst != UINT32_MAX &&
            e->typeConst >= (uint32_t)fn->chunk.constants.count) {
            goto fail;
        }
    }
    for (uint8_t i = 0; i < fn->defaultCount; i++) {
        if (fn->defaultOffsets[i] >= (uint32_t)fn->chunk.count) goto fail;
    }

    if (!rebuildCaches(&fn->chunk)) goto fail;

    jaiGCPopRoots(roots);
    return fn;

fail:
    c->bad = true;
    jaiGCPopRoots(roots);
    return NULL;
}

/* ------------------------------------------------------------------ */
/* Reading: the container                                               */
/* ------------------------------------------------------------------ */

/* Smallest byte count that could hold a header plus a checksum; anything
 * shorter cannot even be probed. */
#define JAIC_MIN_SIZE 32u

/* The escape hatch, and the only way to raise JAI_COMPILER_VERSION.
 *
 * Raising the version wedges the tree in two places at once, and relaxing the
 * seed alone is not enough. The seed serves the PREVIOUS compiler, which stamps
 * the previous version on everything it writes; those fresh images are then read
 * back as cache and refused for declaring the old version. Bumping the C
 * constant first fails that way, and bumping the self-hosted constant first
 * fails the other way, because an image from the future is refused outright. So
 * there is no ordering of a two-constant bump that works while both checks are
 * strict.
 *
 * With this set, both version checks are relaxed for one run -- long enough for
 * `make reseed` to build a seed that stamps the new version, after which nothing
 * needs it again. It deliberately does NOT relax the build id or the source
 * hash: those are what stop a stale image being replayed, and they are still
 * exactly right during a bootstrap.
 *
 * Checked once and warned about once, because the seed is loaded per module and
 * a warning per module would bury the build output it is meant to be visible
 * in. */
static bool jaiSeedAnyVersion(void) {
    static int state = -1;
    if (state < 0) {
        const char *v = getenv("JAITHON_SEED_ANY");
        state = (v != NULL && v[0] != '\0' && v[0] != '0') ? 1 : 0;
        if (state) {
            fprintf(stderr,
                    "warning: JAITHON_SEED_ANY is set -- the seed's minimum "
                    "version is not being enforced.\n"
                    "note: this exists to reseed a wedged tree; run `make "
                    "reseed` and then unset it.\n");
        }
    }
    return state == 1;
}

/* The build id is a *cache* key: it exists so that a rebuilt compiler does not
 * reuse `__jaicache__` entries the previous one wrote. The seed is not a cache.
 * It is compiled into this binary and is regenerated by the *previous* one, so
 * its recorded id is always the previous id and a strict check rejects it
 * always.
 *
 * That is not a small inconvenience: with the C front end gone the seed is the
 * only bootstrap, so a strict check made every edit under `src/vm` unbuildable
 * -- the new binary could not load the seed, and regenerating the seed needed a
 * binary that could run.
 *
 * JAI_COMPILER_VERSION used to be checked strictly for the seed too, on the
 * reasoning that changing the bytecode format means bumping it. That reasoning
 * is self-defeating: bumping it rejected the seed, which left no compiler able
 * to regenerate the seed, so the version could never be bumped and the rule it
 * enforced could never be exercised. The bump this file asks for was impossible
 * to perform.
 *
 * The seed is asked a DIFFERENT question from the cache, because the two want
 * different things:
 *
 *   cache -- must match exactly. It is an optimisation, and replaying bytecode
 *            emitted by a different compiler would run code the source no
 *            longer describes.
 *   seed  -- must merely be RUNNABLE by this binary. Opcodes are append-only
 *            (see OP_COUNT in chunk.h), so every opcode an older compiler could
 *            emit still exists here with the same number and meaning. An older
 *            seed is therefore executable, and that is the whole property
 *            bootstrapping needs.
 *
 * So the seed is accepted from JAI_SEED_MIN_VERSION up to the current version,
 * and refused above it -- an image from the future may use opcodes this binary
 * does not have. JAI_SEED_MIN_VERSION moves only for a change that append-only
 * cannot express (renumbering an opcode, widening an operand), and such a change
 * has to ship a reader for both formats for one release so that the seed can be
 * regenerated across the break. That is the migration this check now permits and
 * previously forbade.
 *
 * JAITHON_SEED_ANY=1 relaxes the floor for one run. It exists so a tree that has
 * wedged itself can always reseed its way out rather than needing a checkout; it
 * warns, and it is never the default. */
static ObjFunction *deserializeWithSidecar(const uint8_t *data, size_t size,
                                           ObjModule *module,
                                           uint64_t expectedHash, bool fromSeed,
                                           const uint8_t *sidecar,
                                           size_t sidecarSize,
                                           size_t sidecarOffset);

static ObjFunction *deserialize(const uint8_t *data, size_t size,
                                ObjModule *module, uint64_t expectedHash,
                                bool fromSeed) {
    return deserializeWithSidecar(data, size, module, expectedHash, fromSeed,
                                  NULL, 0, 0);
}

ObjFunction *jaiDeserializeSeed(const uint8_t *data, size_t size,
                                ObjModule *module, uint64_t expectedHash) {
    return deserialize(data, size, module, expectedHash, true);
}

ObjFunction *jaiDeserializeModule(const uint8_t *data, size_t size,
                                  ObjModule *module, uint64_t expectedHash) {
    return deserialize(data, size, module, expectedHash, false);
}

static ObjFunction *deserializeWithSidecar(const uint8_t *data, size_t size,
                                           ObjModule *module,
                                           uint64_t expectedHash, bool fromSeed,
                                           const uint8_t *sidecar,
                                           size_t sidecarSize,
                                           size_t sidecarOffset) {
    if (data == NULL || module == NULL || size < JAIC_MIN_SIZE) return NULL;
    if (memcmp(data, JAIC_MAGIC, 4) != 0) return NULL;

    /* Integrity first: nothing below parses a byte the checksum has not
     * already vouched for. */
    if (jaiCrc32(data, size - 4) != readU32At(data + size - 4)) return NULL;

    /* The cursor stops short of the checksum, so no parse can wander into it. */
    Cursor c = { data, size - 4, 4, false, 0, NULL, 0, NULL };
    Cursor sidecarCursor = { sidecar, sidecarSize, sidecarOffset, false, 0,
                             NULL, 0, NULL };
    if (sidecar != NULL) c.sidecar = &sidecarCursor;

    /* A RANGE, not an equality. A strict test here is evaluated before the
     * fromSeed branch below, so bumping JAIC_VERSION with it in place refuses
     * every image in boot/seed.bin -- written by the previous generation -- and
     * the tree wedges with "no front end" and no way to build one. */
    uint16_t version = curU16(&c);
    if (version < JAIC_VERSION_MIN || version > JAIC_VERSION) return NULL;
    c.version = version;
    (void)curU16(&c);                                  /* flags, informational */
    uint32_t recordedCompiler = curU32(&c);
    if (jaiSeedAnyVersion()) {
        /* Mid-bump: the running compiler is a generation behind this binary.
         * Everything below still applies, so a stale image is still refused. */
    } else if (fromSeed) {
        /* Runnable, not identical -- see the note above `deserialize`. */
        if (recordedCompiler > JAI_COMPILER_VERSION ||
            recordedCompiler < JAI_SEED_MIN_VERSION) {
            /* Say so. Refusing the seed leaves the tree with no compiler at
             * all, and the caller can only report that a front end is missing
             * -- which describes the symptom and not one word of the cause or
             * the way out. Once, not per module. */
            static bool told = false;
            if (!told) {
                told = true;
                fprintf(stderr,
                        "jaithon: the seed declares compiler version %u; this "
                        "build accepts %u..%u.\n"
                        "note: the seed is the only bootstrap, so nothing can "
                        "compile until this is resolved.\n"
                        "help: JAITHON_SEED_ANY=1 make reseed  -- then rebuild "
                        "and unset it.\n",
                        (unsigned)recordedCompiler,
                        (unsigned)JAI_SEED_MIN_VERSION,
                        (unsigned)JAI_COMPILER_VERSION);
            }
            return NULL;
        }
    } else if (recordedCompiler != JAI_COMPILER_VERSION) {
        return NULL;
    }
    uint32_t recordedBuildId = curU32(&c);
    if (!fromSeed && recordedBuildId != JAI_BUILD_ID) return NULL;
    uint64_t recordedHash = curU64(&c);
    /* The seed is allowed to be out of date with the source beside it. The
     * cache is not.
     *
     * A cache entry whose source has changed must be rejected: it is an
     * optimisation, and running it would run code the file no longer contains.
     * The seed is not an optimisation -- it is the only compiler a fresh tree
     * has, and it is asked for one precisely when the sources HAVE moved.
     * Editing the compiler changes its own source hash, so a hash-strict seed
     * refuses to load exactly when the compiler is being worked on, leaving
     * nothing able to rebuild it. That loop is what made lib/jaithon
     * unmodifiable.
     *
     * A one-generation-old compiler building the new sources is what
     * bootstrapping means, and `make fixpoint-check` is what proves the
     * generation it produces agrees with itself. */
    if (!fromSeed && recordedHash != expectedHash) return NULL;

    uint16_t pathLen = curU16(&c);
    if (!curSkip(&c, pathLen)) return NULL;            /* srcPath */
    (void)curU64(&c);                                  /* mtime, informational */
    if (c.bad) return NULL;

    ValueArray modulePool;
    jaiValueArrayInit(&modulePool);
    int poolRoots = 0;
    ObjFunction *body = NULL;
    bool ok = true;

    /* The string table comes before the pools, because every K_STRREF in them
     * indexes it. Its root range stays pushed for the whole read and is popped
     * on every exit below. */
    if (version >= JAIC_VERSION_STRTAB) {
        ok = readStrTab(&c);
    }

    uint32_t poolCount = ok ? curU32(&c) : 0;
    if (ok && (c.bad || poolCount >= JAIC_CONST_MAX ||
               !curFits(&c, poolCount, 1))) {
        ok = false;
    }
    if (ok) {
        ok = readConstantPool(&c, module, &modulePool, poolCount, 0, &poolRoots);
    }

    if (ok) {
        body = readFunction(&c, module, 0);
        ok = body != NULL;
    }
    if (ok) {
        jaiGCPushRoot(OBJ_VAL(body));
        poolRoots++;
    }

    /* Exports are collected before anything is written to `module`: a failure
     * anywhere must leave it exactly as it was. */
    uint32_t exportCount = 0;
    uint32_t *exportIndices = NULL;
    if (ok) {
        exportCount = curU32(&c);
        if (c.bad || !curFits(&c, exportCount, JAIC_U32_ENTRY)) {
            ok = false;
        } else if (exportCount > 0) {
            exportIndices = JAI_ALLOC(uint32_t, exportCount);
            for (uint32_t i = 0; i < exportCount; i++) {
                exportIndices[i] = curU32(&c);
                if (poolString(&modulePool, exportIndices[i]) == NULL) ok = false;
            }
            if (c.bad) ok = false;
        }
    }

    if (ok) {
        uint32_t importCount = curU32(&c);
        /* Nothing consumes the import list yet, but it must be present and
         * well-formed for the file to be considered whole. */
        if (c.bad || !curFits(&c, importCount, 2 * JAIC_U32_ENTRY)) {
            ok = false;
        } else {
            for (uint32_t i = 0; i < importCount && ok; i++) {
                uint32_t pathIndex = curU32(&c);
                uint32_t aliasIndex = curU32(&c);
                if (c.bad) { ok = false; break; }
                if (poolString(&modulePool, pathIndex) == NULL) ok = false;
                if (aliasIndex != JAIC_NO_NAME &&
                    poolString(&modulePool, aliasIndex) == NULL) {
                    ok = false;
                }
            }
        }
    }

    /* Trailing bytes between the last section and the checksum mean this is
     * not the file this reader thinks it is. */
    if (ok && (c.bad || c.pos != c.size)) ok = false;

    if (ok) {
        for (uint32_t i = 0; i < exportCount; i++) {
            ObjString *name = poolString(&modulePool, exportIndices[i]);
            (void)jaiTableSetInterned(&module->exports, name, BOOL_VAL(true));
        }
    }

    if (exportIndices != NULL) {
        JAI_FREE_ARRAY(uint32_t, exportIndices, exportCount);
    }
    jaiValueArrayFree(&modulePool);
    jaiGCPopRoots(poolRoots);
    if (c.strings != NULL) {
        /* Popped only here: every constant pool now holds its own reference to
         * each string, so the range has done its job. */
        jaiGCPopRootRange();
        JAI_FREE_ARRAY(Value, c.strings, c.stringCount);
    }
    return ok ? body : NULL;
}

/* ------------------------------------------------------------------ */
/* Cache files                                                          */
/* ------------------------------------------------------------------ */

uint64_t jaiSourceHash(const char *source, size_t length) {
    return jaiHashBytes(source, source != NULL ? length : 0);
}

uint32_t jaiBuildId(void) { return JAI_BUILD_ID; }

void jaiCachePathFor(const char *sourcePath, char *out, size_t outSize) {
    if (out == NULL || outSize == 0) return;
    out[0] = '\0';
    if (sourcePath == NULL || sourcePath[0] == '\0') return;

    char dir[JAI_MAX_PATH];
    char base[JAI_MAX_PATH];
    jaiPathDirname(dir, sizeof dir, sourcePath);
    jaiPathBasename(base, sizeof base, sourcePath);
    if (dir[0] == '\0' || base[0] == '\0') return;
    if (strcmp(base, ".") == 0 || strcmp(base, "..") == 0 ||
        strcmp(base, "/") == 0) {
        return;
    }

    /* "src/util.jai" -> "src/__jaicache__/util.jaic". */
    size_t len = strlen(base);
    size_t extLen = strlen(JAIC_SOURCE_EXT);
    if (len > extLen && memcmp(base + len - extLen, JAIC_SOURCE_EXT, extLen) == 0) {
        len -= extLen;
        base[len] = '\0';
    }
    if (len == 0) return;

    char cacheDir[JAI_MAX_PATH];
    jaiPathJoin(cacheDir, sizeof cacheDir, dir, JAIC_CACHE_DIR);
    if (cacheDir[0] == '\0') return;

    char file[JAI_MAX_PATH];
    int written = snprintf(file, sizeof file, "%s%s", base, JAIC_SUFFIX);
    if (written < 0 || (size_t)written >= sizeof file) return;

    /* jaiPathJoin empties `out` rather than truncating, which is what the
     * callers below test for. */
    jaiPathJoin(out, outSize, cacheDir, file);
}

/* "…/util.jaic" -> "…/util.jaid". False when it does not fit. */
static bool sidecarPathFor(const char *cachePath, char *out, size_t outSize) {
    size_t len = strlen(cachePath);
    size_t extLen = strlen(JAIC_SUFFIX);
    if (len <= extLen || len + 1 > outSize) return false;
    if (memcmp(cachePath + len - extLen, JAIC_SUFFIX, extLen) != 0) return false;
    memcpy(out, cachePath, len);
    memcpy(out + len - extLen, JAID_SUFFIX, extLen);
    out[len] = '\0';
    return true;
}

bool jaiCacheStore(const char *sourcePath, ObjModule *module,
                   ObjFunction *body, uint64_t sourceHash, uint32_t flags) {
    char path[JAI_MAX_PATH];
    jaiCachePathFor(sourcePath, path, sizeof path);
    if (path[0] == '\0') return false;

    char dir[JAI_MAX_PATH];
    jaiPathDirname(dir, sizeof dir, path);
    if (dir[0] == '\0' || !jaiMakeDirs(dir)) return false;

    size_t size = 0, sidecarSize = 0;
    uint8_t *sidecar = NULL;
    uint8_t *data = jaiSerializeModule(module, body, sourceHash, flags, &size,
                                       &sidecar, &sidecarSize);
    if (data == NULL) return false;

    /* Best effort, and deliberately before the image is renamed into place: a
     * .jaid without its .jaic is inert, whereas a .jaic whose .jaid never
     * arrived would silently lose spans. A failure here costs source spans in
     * release tracebacks and nothing else, so it does not fail the store. */
    if (sidecar != NULL) {
        char sidecarPath[JAI_MAX_PATH];
        if (sidecarPathFor(path, sidecarPath, sizeof sidecarPath)) {
            (void)jaiWriteFile(sidecarPath, sidecar, sidecarSize);
        }
        (void)jaiRealloc(sidecar, sidecarSize, 0);
    } else {
        /* A debug rebuild over a stripped one must not leave the old sidecar
         * behind: its records would no longer line up. */
        char sidecarPath[JAI_MAX_PATH];
        if (sidecarPathFor(path, sidecarPath, sizeof sidecarPath)) {
            (void)unlink(sidecarPath);
        }
    }

    /* Write to a pid-tagged temporary and rename: rename is atomic within a
     * directory, so a concurrent reader sees either the old file or the whole
     * new one, never a partial write. */
    char tmp[JAI_MAX_PATH];
    int written = snprintf(tmp, sizeof tmp, "%s.tmp%ld", path, (long)getpid());
    if (written < 0 || (size_t)written >= sizeof tmp) {
        (void)jaiRealloc(data, size, 0);
        return false;
    }

    bool ok = jaiWriteFile(tmp, data, size);
    (void)jaiRealloc(data, size, 0);
    if (!ok) {
        (void)unlink(tmp);
        return false;
    }
    if (rename(tmp, path) != 0) {
        (void)unlink(tmp);
        return false;
    }
    return true;
}

uint8_t *jaiCacheRead(const char *sourcePath, size_t *outLength) {
    char path[JAI_MAX_PATH];
    jaiCachePathFor(sourcePath, path, sizeof path);
    if (path[0] == '\0') return NULL;

    size_t length = 0;
    char *data = jaiReadFile(path, &length);
    if (data == NULL) return NULL;

    *outLength = length;
    return (uint8_t *)data;
}

void jaiCacheReadFree(uint8_t *data, size_t length) {
    /* jaiReadFile allocates length + 1 for its terminator; freeing the wrong
     * size corrupts the allocator's accounting, which is what decides when the
     * collector runs. */
    if (data != NULL) (void)jaiRealloc(data, length + 1, 0);
}

/* The .jaid beside `sourcePath`'s image, validated and positioned past its
 * header, or NULL. Never an error: an absent, stale or corrupt sidecar costs
 * source spans in tracebacks, nothing more. */
uint8_t *jaiSidecarRead(const char *sourcePath, uint64_t sourceHash,
                        size_t *outLength, size_t *outOffset) {
    char path[JAI_MAX_PATH];
    char sidecarPath[JAI_MAX_PATH];
    jaiCachePathFor(sourcePath, path, sizeof path);
    if (path[0] == '\0') return NULL;
    if (!sidecarPathFor(path, sidecarPath, sizeof sidecarPath)) return NULL;

    size_t length = 0;
    char *data = jaiReadFile(sidecarPath, &length);
    if (data == NULL) return NULL;

    const uint8_t *p = (const uint8_t *)data;
    bool ok = length >= JAID_HEADER + 4 &&
              memcmp(p, JAID_MAGIC, 4) == 0 &&
              ((uint16_t)p[4] | (uint16_t)(p[5] << 8)) == JAID_VERSION &&
              jaiCrc32(p, length - 4) == readU32At(p + length - 4);
    if (ok) {
        uint64_t recorded = 0;
        for (int i = 0; i < 8; i++) recorded |= (uint64_t)p[8 + i] << (8 * i);
        /* The tie to its image. Records are matched by position, so a sidecar
         * from a different compile would silently attach the wrong spans. */
        ok = recorded == sourceHash;
    }
    if (!ok) {
        (void)jaiRealloc(data, length + 1, 0);
        return NULL;
    }

    *outLength = length - 4;      /* the cursor stops short of the checksum */
    *outOffset = JAID_HEADER;
    return (uint8_t *)data;
}

ObjFunction *jaiDeserializeCached(const uint8_t *data, size_t size,
                                  ObjModule *module, uint64_t sourceHash,
                                  const char *sourcePath) {
    size_t sidecarLen = 0, sidecarOffset = 0;
    uint8_t *sidecar = jaiSidecarRead(sourcePath, sourceHash, &sidecarLen,
                                      &sidecarOffset);

    ObjFunction *fn = deserializeWithSidecar(data, size, module, sourceHash,
                                             false, sidecar, sidecarLen,
                                             sidecarOffset);
    if (sidecar != NULL) {
        /* jaiReadFile allocated sidecarLen + 4 (checksum) + 1 (terminator). */
        (void)jaiRealloc(sidecar, sidecarLen + 5, 0);
    }
    return fn;
}

ObjFunction *jaiCacheLoad(const char *sourcePath, ObjModule *module,
                          uint64_t sourceHash) {
    size_t length = 0;
    uint8_t *data = jaiCacheRead(sourcePath, &length);
    if (data == NULL) return NULL;

    ObjFunction *fn = jaiDeserializeCached(data, length, module, sourceHash,
                                           sourcePath);
    jaiCacheReadFree(data, length);
    return fn;
}

static bool hasSuffix(const char *s, const char *suffix) {
    size_t sl = strlen(s), fl = strlen(suffix);
    return sl >= fl && memcmp(s + sl - fl, suffix, fl) == 0;
}

/* Deletes the artefacts this module creates — cache files and any temporary
 * left behind by an interrupted store — then the directory if it is now
 * empty. Foreign files are left alone. */
static void clearCacheDir(const char *dir) {
    DIR *d = opendir(dir);
    if (d == NULL) return;

    for (struct dirent *e = readdir(d); e != NULL; e = readdir(d)) {
        if (strcmp(e->d_name, ".") == 0 || strcmp(e->d_name, "..") == 0) continue;
        if (!hasSuffix(e->d_name, JAIC_SUFFIX) &&
            strstr(e->d_name, JAIC_SUFFIX ".tmp") == NULL) {
            continue;
        }

        char path[JAI_MAX_PATH];
        jaiPathJoin(path, sizeof path, dir, e->d_name);
        if (path[0] == '\0') continue;

        struct stat st;
        if (lstat(path, &st) != 0 || !S_ISREG(st.st_mode)) continue;
        (void)unlink(path);
    }
    (void)closedir(d);
    (void)rmdir(dir);   /* succeeds only if nothing else was in there */
}

static void clearCacheTree(const char *dir, int depth) {
    if (depth > 32) return;   /* a symlink loop cannot be walked forever */

    DIR *d = opendir(dir);
    if (d == NULL) return;

    for (struct dirent *e = readdir(d); e != NULL; e = readdir(d)) {
        if (strcmp(e->d_name, ".") == 0 || strcmp(e->d_name, "..") == 0) continue;

        char path[JAI_MAX_PATH];
        jaiPathJoin(path, sizeof path, dir, e->d_name);
        if (path[0] == '\0') continue;

        /* lstat, not stat: a symlinked directory is not descended into, so a
         * clear can never delete outside the tree it was given. */
        struct stat st;
        if (lstat(path, &st) != 0 || !S_ISDIR(st.st_mode)) continue;

        if (strcmp(e->d_name, JAIC_CACHE_DIR) == 0) {
            clearCacheDir(path);
        } else {
            clearCacheTree(path, depth + 1);
        }
    }
    (void)closedir(d);
}

void jaiCacheClear(const char *rootDir) {
    if (rootDir == NULL || rootDir[0] == '\0') return;
    if (!jaiPathIsDir(rootDir)) return;

    char base[JAI_MAX_PATH];
    jaiPathBasename(base, sizeof base, rootDir);
    if (strcmp(base, JAIC_CACHE_DIR) == 0) {
        clearCacheDir(rootDir);
        return;
    }
    clearCacheTree(rootDir, 0);
}
