/* serialize_internal.h — the .jaic container's feature macros, includes and
 * on-disk constants, shared by the writer, the reader and the cache layer.
 * The container itself is documented at the top of serialize.c. */
#ifndef JAI_SERIALIZE_INTERNAL_H
#define JAI_SERIALIZE_INTERNAL_H

/* Feature macros must precede every include: getpid/unlink/rmdir/lstat and
 * <dirent.h> are POSIX, not C11. */
#if !defined(_POSIX_C_SOURCE)
#  define _POSIX_C_SOURCE 200809L
#endif
#if defined(__APPLE__) && !defined(_DARWIN_C_SOURCE)
#  define _DARWIN_C_SOURCE
#endif

#include "vm/bytecode/serialize.h"

#include "vm/bytecode/verify.h"

#include <dirent.h>
#include <limits.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>

#include "vm/bytecode/chunk.h"
#include "vm/gc.h"
#include "vm/object/object.h"

/* Generated by the Makefile from a hash of every source file under src/.
 * JAI_COMPILER_VERSION is hand-maintained and was repeatedly forgotten, so a
 * newer compiler silently replayed bytecode an older one had written. This
 * makes that impossible: any source edit invalidates every cached image. */
#include "jai_build_id.h"
#include "vm/table.h"

/* Constant-pool tags (spec §4). 7 and 9 are missing on purpose: they were a
 * class-spec record and a serialised type descriptor, and neither is written by
 * either front end. They are not free, though -- jaic.jai still DECODES them --
 * so a new tag takes the next unused number rather than reusing one. That is
 * what keeps "a tag this reader does not know" always a newer format and never
 * an older one misread. An unknown tag refuses the image, which recompiles. */
typedef enum {
    K_NULL  = 0,
    K_BOOL  = 1,
    K_INT   = 2,
    K_FLOAT = 3,
    K_STR   = 4,
    K_BYTES = 5,
    K_FUNC  = 6,
    K_TUPLE = 8,
    /* An index into the module's string table (§4). From JAIC_VERSION_STRTAB on
     * this replaces K_STR everywhere: 62.5% of a .jaic's string payload was one
     * text repeated across nested function pools, and 94.9% of strings are
     * under 16 bytes yet each paid a 4-byte u32 length. K_STR stays defined
     * because older containers still use it.
     *
     * 10, NOT 7. The header above says 7 and 9 were never written by either
     * front end; that is true of the writers and false of the readers.
     * lib/jaithon/compile/jaic.jai decodes 7 as a class-spec record and 9 as a
     * type descriptor, so claiming 7 here would have made the two
     * implementations disagree about the same byte, silently, in the one
     * direction nothing in the tree compares. */
    K_STRREF = 10,
} ConstTag;

#define JAIC_CACHE_DIR   "__jaicache__"
#define JAIC_SUFFIX      ".jaic"
#define JAIC_SOURCE_EXT  ".jai"

/* The debug sidecar: the line tables a stripped .jaic left out, beside it under
 * the same stem. Its own magic and checksum, and its srcHash must equal the
 * image's -- a .jaid that does not match is ignored rather than lined up
 * against the wrong records. Missing entirely is not an error: a release
 * install can simply not ship them, and tracebacks fall back to function name
 * plus code offset. */
#define JAID_MAGIC       "JAID"
#define JAID_VERSION     1u
#define JAID_SUFFIX      ".jaid"
#define JAID_HEADER      16u   /* magic 4, version 2, reserved 2, srcHash 8 */

/* A function record has no name when its nameIndex is this sentinel; §5 has no
 * other way to say "unnamed", and index 0 is a perfectly good constant. */
#define JAIC_NO_NAME     UINT32_MAX

/* Nesting bound for FUNC/TUPLE records. Deep nesting is legitimate but a
 * crafted file must not be able to recurse the C stack to death. */
#define JAIC_MAX_DEPTH   64

/* Matches the u24 constant operand: a pool can never exceed this. */
#define JAIC_CONST_MAX   (1u << 24)

/* On-disk sizes of the fixed-width records, used to bound counts against the
 * bytes actually left in the buffer before anything is allocated. */
#define JAIC_LINE_ENTRY   12u   /* u32 offset, u32 span, u32 spanEnd */
#define JAIC_EXC_ENTRY    16u   /* u32 start, end, handler, typeConst */
#define JAIC_U32_ENTRY     4u

/* Flag bits an ObjFunction may carry. Anything else is a newer compiler's
 * output that this reader would silently misinterpret. */
#define JAIC_KNOWN_FN_FLAGS ((uint32_t)0xFFu | (uint32_t)FN_INIT | (uint32_t)FN_TRACE | (uint32_t)FN_GPU_KERNEL)

uint32_t readU32At(const uint8_t *p);

ObjFunction *deserializeWithSidecar(const uint8_t *data, size_t size,
                                    ObjModule *module,
                                    uint64_t expectedHash, bool fromSeed,
                                    const uint8_t *sidecar,
                                    size_t sidecarSize,
                                    size_t sidecarOffset);

#endif /* JAI_SERIALIZE_INTERNAL_H */
