#!/usr/bin/env python3
"""Turn the public-domain Hershey font distribution into a jaicv module.

The Hershey Fonts were originally created by Dr. A. V. Hershey while working
at the U. S. National Bureau of Standards. The format of the font data used
here was originally created by James Hurt, Cognition, Inc., 900 Technology
Park Drive, Billerica, MA 01821. Both acknowledgements are required by the
distribution's terms and are reproduced in the generated module.

Usage:  hershey_to_jai.py <directory of .jhf files> <output .jai>

A .jhf record is five characters of glyph number, three of vertex count, then
two characters a vertex, each holding a coordinate as `character - 'R'`. The
first pair is the glyph's left and right bearing rather than a point, and the
pair `" R"` lifts the pen. Records wrap at 72 columns, so the parser counts
characters rather than trusting line boundaries.
"""
from __future__ import annotations

import sys
from pathlib import Path

#: OpenCV's font faces, in its own numbering, and the Hershey file each one
#: draws from. PLAIN and COMPLEX_SMALL share their glyphs with another face
#: and differ only in the scale `put_text` renders them at.
FACES = [
    ("SIMPLEX", "futural"),
    ("PLAIN", "futural"),
    ("DUPLEX", "futuram"),
    ("COMPLEX", "rowmand"),
    ("TRIPLEX", "rowmant"),
    ("COMPLEX_SMALL", "rowmans"),
    ("SCRIPT_SIMPLEX", "scripts"),
    ("SCRIPT_COMPLEX", "scriptc"),
]

FIRST_CHAR = 32
GLYPH_COUNT = 96


def parse(text: str) -> list[str]:
    """Split a .jhf into one raw coordinate string a glyph."""
    body = "".join(text.split("\n"))
    glyphs: list[str] = []
    at = 0
    while at + 8 <= len(body):
        if not body[at:at + 8].strip():
            break
        count = int(body[at + 5:at + 8])
        start = at + 8
        glyphs.append(body[start:start + 2 * count])
        at = start + 2 * count
    return glyphs


def jai_string(raw: str) -> str:
    return '"' + raw.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    source, out = Path(sys.argv[1]), Path(sys.argv[2])

    seen: dict[str, list[str]] = {}
    for _face, stem in FACES:
        if stem in seen:
            continue
        glyphs = parse((source / f"{stem}.jhf").read_text())
        if len(glyphs) < GLYPH_COUNT:
            print(f"{stem}: {len(glyphs)} glyphs, expected {GLYPH_COUNT}",
                  file=sys.stderr)
            return 1
        seen[stem] = glyphs[:GLYPH_COUNT]

    lines = [
        "#: Hershey vector font data, one entry a glyph for ASCII 32 through 127.",
        "#:",
        "#: The Hershey Fonts were originally created by Dr. A. V. Hershey while",
        "#: working at the U. S. National Bureau of Standards.",
        "#:",
        "#: The format of the font data in this distribution was originally created",
        "#: by James Hurt, Cognition, Inc., 900 Technology Park Drive, Billerica,",
        "#: MA 01821.",
        "#:",
        "#: Generated by `tools/hershey_to_jai.py` from that distribution. Each",
        "#: string holds two characters a vertex, every coordinate stored as",
        "#: `character - 'R'`; the first pair is the glyph's left and right bearing",
        "#: rather than a point, and the pair `\" R\"` lifts the pen. `text.jai`",
        "#: decodes these once and caches the result.",
        "#:",
        "#: Do not edit by hand.",
        "",
        f"pub let FIRST_CHAR = {FIRST_CHAR}",
        f"pub let GLYPH_COUNT = {GLYPH_COUNT}",
        "",
    ]
    for stem, glyphs in seen.items():
        lines.append(f"pub let {stem.upper()} = [")
        for glyph in glyphs:
            lines.append(f"    {jai_string(glyph)},")
        lines.append("]")
        lines.append("")

    lines.append("#: Indexed by the `FONT_HERSHEY_*` face numbers.")
    lines.append("pub fn face_glyphs(face: int) -> list[str] {")
    lines.append("    let tables = [")
    for _face, stem in FACES:
        lines.append(f"        {stem.upper()},")
    lines.append("    ]")
    lines.append("    if face < 0 or face >= tables.len() { return tables[0] }")
    lines.append("    return tables[face]")
    lines.append("}")
    out.write_text("\n".join(lines) + "\n")
    total = sum(len(g) for gs in seen.values() for g in gs)
    print(f"{out}: {len(seen)} fonts, {total} coordinate characters")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
